[tools]
go = "1.26"
"go:github.com/golang-migrate/migrate/v4/cmd/migrate" = { version = "latest", tags = "postgres" }
golangci-lint = "2.11.4"
mockery = "latest"
oapi-codegen = "latest"
sqlc = "latest"
