micronaut.application.name = 'systemofadownload'
liquibase.datasources.default.change-log = 'classpath:db/liquibase-changelog.xml'
jpa.default.reactive = false
netty.default.allocator.max-order = 3

[r2dbc.datasources.default]
url = 'r2dbc:postgresql://localhost:5432/postgres'
username = 'postgres'
password = ''
dialect = 'POSTGRES'

[micronaut.router.static-resources.swagger]
paths = 'classpath:META-INF/swagger'
mapping = '/swagger/**'

[micronaut.router.static-resources.swagger-ui]
paths = 'classpath:META-INF/swagger/views/swagger-ui'
mapping = '/swagger-ui/**'

micronaut.security.enabled=false
