// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package app

import (
	"context"

	"github.com/spongepowered/systemofadownload/internal/app"
	"github.com/spongepowered/systemofadownload/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateArtifact provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateArtifact(ctx context.Context, arg db.CreateArtifactParams) (db.Artifact, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateArtifact")
	}

	var r0 db.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactParams) (db.Artifact, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactParams) db.Artifact); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateArtifactParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArtifact'
type MockRepository_CreateArtifact_Call struct {
	*mock.Call
}

// CreateArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateArtifactParams
func (_e *MockRepository_Expecter) CreateArtifact(ctx interface{}, arg interface{}) *MockRepository_CreateArtifact_Call {
	return &MockRepository_CreateArtifact_Call{Call: _e.mock.On("CreateArtifact", ctx, arg)}
}

func (_c *MockRepository_CreateArtifact_Call) Run(run func(ctx context.Context, arg db.CreateArtifactParams)) *MockRepository_CreateArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateArtifactParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateArtifactParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateArtifact_Call) Return(artifact db.Artifact, err error) *MockRepository_CreateArtifact_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *MockRepository_CreateArtifact_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateArtifactParams) (db.Artifact, error)) *MockRepository_CreateArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// CreateArtifactVersion provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateArtifactVersion(ctx context.Context, arg db.CreateArtifactVersionParams) (db.ArtifactVersion, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateArtifactVersion")
	}

	var r0 db.ArtifactVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactVersionParams) (db.ArtifactVersion, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactVersionParams) db.ArtifactVersion); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ArtifactVersion)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateArtifactVersionParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateArtifactVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArtifactVersion'
type MockRepository_CreateArtifactVersion_Call struct {
	*mock.Call
}

// CreateArtifactVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateArtifactVersionParams
func (_e *MockRepository_Expecter) CreateArtifactVersion(ctx interface{}, arg interface{}) *MockRepository_CreateArtifactVersion_Call {
	return &MockRepository_CreateArtifactVersion_Call{Call: _e.mock.On("CreateArtifactVersion", ctx, arg)}
}

func (_c *MockRepository_CreateArtifactVersion_Call) Run(run func(ctx context.Context, arg db.CreateArtifactVersionParams)) *MockRepository_CreateArtifactVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateArtifactVersionParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateArtifactVersionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateArtifactVersion_Call) Return(artifactVersion db.ArtifactVersion, err error) *MockRepository_CreateArtifactVersion_Call {
	_c.Call.Return(artifactVersion, err)
	return _c
}

func (_c *MockRepository_CreateArtifactVersion_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateArtifactVersionParams) (db.ArtifactVersion, error)) *MockRepository_CreateArtifactVersion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateArtifactVersionAsset provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateArtifactVersionAsset(ctx context.Context, arg db.CreateArtifactVersionAssetParams) (db.ArtifactVersionedAsset, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateArtifactVersionAsset")
	}

	var r0 db.ArtifactVersionedAsset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactVersionAssetParams) (db.ArtifactVersionedAsset, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactVersionAssetParams) db.ArtifactVersionedAsset); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ArtifactVersionedAsset)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateArtifactVersionAssetParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateArtifactVersionAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArtifactVersionAsset'
type MockRepository_CreateArtifactVersionAsset_Call struct {
	*mock.Call
}

// CreateArtifactVersionAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateArtifactVersionAssetParams
func (_e *MockRepository_Expecter) CreateArtifactVersionAsset(ctx interface{}, arg interface{}) *MockRepository_CreateArtifactVersionAsset_Call {
	return &MockRepository_CreateArtifactVersionAsset_Call{Call: _e.mock.On("CreateArtifactVersionAsset", ctx, arg)}
}

func (_c *MockRepository_CreateArtifactVersionAsset_Call) Run(run func(ctx context.Context, arg db.CreateArtifactVersionAssetParams)) *MockRepository_CreateArtifactVersionAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateArtifactVersionAssetParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateArtifactVersionAssetParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateArtifactVersionAsset_Call) Return(artifactVersionedAsset db.ArtifactVersionedAsset, err error) *MockRepository_CreateArtifactVersionAsset_Call {
	_c.Call.Return(artifactVersionedAsset, err)
	return _c
}

func (_c *MockRepository_CreateArtifactVersionAsset_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateArtifactVersionAssetParams) (db.ArtifactVersionedAsset, error)) *MockRepository_CreateArtifactVersionAsset_Call {
	_c.Call.Return(run)
	return _c
}

// CreateArtifactVersionTag provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateArtifactVersionTag(ctx context.Context, arg db.CreateArtifactVersionTagParams) (db.ArtifactVersionedTag, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateArtifactVersionTag")
	}

	var r0 db.ArtifactVersionedTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactVersionTagParams) (db.ArtifactVersionedTag, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactVersionTagParams) db.ArtifactVersionedTag); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ArtifactVersionedTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateArtifactVersionTagParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateArtifactVersionTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArtifactVersionTag'
type MockRepository_CreateArtifactVersionTag_Call struct {
	*mock.Call
}

// CreateArtifactVersionTag is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateArtifactVersionTagParams
func (_e *MockRepository_Expecter) CreateArtifactVersionTag(ctx interface{}, arg interface{}) *MockRepository_CreateArtifactVersionTag_Call {
	return &MockRepository_CreateArtifactVersionTag_Call{Call: _e.mock.On("CreateArtifactVersionTag", ctx, arg)}
}

func (_c *MockRepository_CreateArtifactVersionTag_Call) Run(run func(ctx context.Context, arg db.CreateArtifactVersionTagParams)) *MockRepository_CreateArtifactVersionTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateArtifactVersionTagParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateArtifactVersionTagParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateArtifactVersionTag_Call) Return(artifactVersionedTag db.ArtifactVersionedTag, err error) *MockRepository_CreateArtifactVersionTag_Call {
	_c.Call.Return(artifactVersionedTag, err)
	return _c
}

func (_c *MockRepository_CreateArtifactVersionTag_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateArtifactVersionTagParams) (db.ArtifactVersionedTag, error)) *MockRepository_CreateArtifactVersionTag_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroup provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateGroup(ctx context.Context, arg db.CreateGroupParams) (db.Group, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 db.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateGroupParams) (db.Group, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateGroupParams) db.Group); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Group)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateGroupParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockRepository_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateGroupParams
func (_e *MockRepository_Expecter) CreateGroup(ctx interface{}, arg interface{}) *MockRepository_CreateGroup_Call {
	return &MockRepository_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, arg)}
}

func (_c *MockRepository_CreateGroup_Call) Run(run func(ctx context.Context, arg db.CreateGroupParams)) *MockRepository_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateGroupParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateGroupParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateGroup_Call) Return(group db.Group, err error) *MockRepository_CreateGroup_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockRepository_CreateGroup_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateGroupParams) (db.Group, error)) *MockRepository_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtifactByGroupAndId provides a mock function for the type MockRepository
func (_mock *MockRepository) GetArtifactByGroupAndId(ctx context.Context, arg db.GetArtifactByGroupAndIdParams) (db.Artifact, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactByGroupAndId")
	}

	var r0 db.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetArtifactByGroupAndIdParams) (db.Artifact, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetArtifactByGroupAndIdParams) db.Artifact); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.GetArtifactByGroupAndIdParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetArtifactByGroupAndId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtifactByGroupAndId'
type MockRepository_GetArtifactByGroupAndId_Call struct {
	*mock.Call
}

// GetArtifactByGroupAndId is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetArtifactByGroupAndIdParams
func (_e *MockRepository_Expecter) GetArtifactByGroupAndId(ctx interface{}, arg interface{}) *MockRepository_GetArtifactByGroupAndId_Call {
	return &MockRepository_GetArtifactByGroupAndId_Call{Call: _e.mock.On("GetArtifactByGroupAndId", ctx, arg)}
}

func (_c *MockRepository_GetArtifactByGroupAndId_Call) Run(run func(ctx context.Context, arg db.GetArtifactByGroupAndIdParams)) *MockRepository_GetArtifactByGroupAndId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.GetArtifactByGroupAndIdParams
		if args[1] != nil {
			arg1 = args[1].(db.GetArtifactByGroupAndIdParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetArtifactByGroupAndId_Call) Return(artifact db.Artifact, err error) *MockRepository_GetArtifactByGroupAndId_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *MockRepository_GetArtifactByGroupAndId_Call) RunAndReturn(run func(ctx context.Context, arg db.GetArtifactByGroupAndIdParams) (db.Artifact, error)) *MockRepository_GetArtifactByGroupAndId_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtifactVersion provides a mock function for the type MockRepository
func (_mock *MockRepository) GetArtifactVersion(ctx context.Context, arg db.GetArtifactVersionParams) (db.ArtifactVersion, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactVersion")
	}

	var r0 db.ArtifactVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetArtifactVersionParams) (db.ArtifactVersion, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetArtifactVersionParams) db.ArtifactVersion); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ArtifactVersion)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.GetArtifactVersionParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetArtifactVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtifactVersion'
type MockRepository_GetArtifactVersion_Call struct {
	*mock.Call
}

// GetArtifactVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetArtifactVersionParams
func (_e *MockRepository_Expecter) GetArtifactVersion(ctx interface{}, arg interface{}) *MockRepository_GetArtifactVersion_Call {
	return &MockRepository_GetArtifactVersion_Call{Call: _e.mock.On("GetArtifactVersion", ctx, arg)}
}

func (_c *MockRepository_GetArtifactVersion_Call) Run(run func(ctx context.Context, arg db.GetArtifactVersionParams)) *MockRepository_GetArtifactVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.GetArtifactVersionParams
		if args[1] != nil {
			arg1 = args[1].(db.GetArtifactVersionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetArtifactVersion_Call) Return(artifactVersion db.ArtifactVersion, err error) *MockRepository_GetArtifactVersion_Call {
	_c.Call.Return(artifactVersion, err)
	return _c
}

func (_c *MockRepository_GetArtifactVersion_Call) RunAndReturn(run func(ctx context.Context, arg db.GetArtifactVersionParams) (db.ArtifactVersion, error)) *MockRepository_GetArtifactVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroup provides a mock function for the type MockRepository
func (_mock *MockRepository) GetGroup(ctx context.Context, mavenID string) (db.Group, error) {
	ret := _mock.Called(ctx, mavenID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroup")
	}

	var r0 db.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (db.Group, error)); ok {
		return returnFunc(ctx, mavenID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) db.Group); ok {
		r0 = returnFunc(ctx, mavenID)
	} else {
		r0 = ret.Get(0).(db.Group)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, mavenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroup'
type MockRepository_GetGroup_Call struct {
	*mock.Call
}

// GetGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - mavenID string
func (_e *MockRepository_Expecter) GetGroup(ctx interface{}, mavenID interface{}) *MockRepository_GetGroup_Call {
	return &MockRepository_GetGroup_Call{Call: _e.mock.On("GetGroup", ctx, mavenID)}
}

func (_c *MockRepository_GetGroup_Call) Run(run func(ctx context.Context, mavenID string)) *MockRepository_GetGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetGroup_Call) Return(group db.Group, err error) *MockRepository_GetGroup_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockRepository_GetGroup_Call) RunAndReturn(run func(ctx context.Context, mavenID string) (db.Group, error)) *MockRepository_GetGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GroupExistsByMavenID provides a mock function for the type MockRepository
func (_mock *MockRepository) GroupExistsByMavenID(ctx context.Context, lower string) (bool, error) {
	ret := _mock.Called(ctx, lower)

	if len(ret) == 0 {
		panic("no return value specified for GroupExistsByMavenID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, lower)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, lower)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, lower)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GroupExistsByMavenID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupExistsByMavenID'
type MockRepository_GroupExistsByMavenID_Call struct {
	*mock.Call
}

// GroupExistsByMavenID is a helper method to define mock.On call
//   - ctx context.Context
//   - lower string
func (_e *MockRepository_Expecter) GroupExistsByMavenID(ctx interface{}, lower interface{}) *MockRepository_GroupExistsByMavenID_Call {
	return &MockRepository_GroupExistsByMavenID_Call{Call: _e.mock.On("GroupExistsByMavenID", ctx, lower)}
}

func (_c *MockRepository_GroupExistsByMavenID_Call) Run(run func(ctx context.Context, lower string)) *MockRepository_GroupExistsByMavenID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GroupExistsByMavenID_Call) Return(b bool, err error) *MockRepository_GroupExistsByMavenID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_GroupExistsByMavenID_Call) RunAndReturn(run func(ctx context.Context, lower string) (bool, error)) *MockRepository_GroupExistsByMavenID_Call {
	_c.Call.Return(run)
	return _c
}

// ListArtifactVersionAssets provides a mock function for the type MockRepository
func (_mock *MockRepository) ListArtifactVersionAssets(ctx context.Context, artifactVersionID int64) ([]db.ArtifactVersionedAsset, error) {
	ret := _mock.Called(ctx, artifactVersionID)

	if len(ret) == 0 {
		panic("no return value specified for ListArtifactVersionAssets")
	}

	var r0 []db.ArtifactVersionedAsset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]db.ArtifactVersionedAsset, error)); ok {
		return returnFunc(ctx, artifactVersionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []db.ArtifactVersionedAsset); ok {
		r0 = returnFunc(ctx, artifactVersionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ArtifactVersionedAsset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, artifactVersionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListArtifactVersionAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArtifactVersionAssets'
type MockRepository_ListArtifactVersionAssets_Call struct {
	*mock.Call
}

// ListArtifactVersionAssets is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactVersionID int64
func (_e *MockRepository_Expecter) ListArtifactVersionAssets(ctx interface{}, artifactVersionID interface{}) *MockRepository_ListArtifactVersionAssets_Call {
	return &MockRepository_ListArtifactVersionAssets_Call{Call: _e.mock.On("ListArtifactVersionAssets", ctx, artifactVersionID)}
}

func (_c *MockRepository_ListArtifactVersionAssets_Call) Run(run func(ctx context.Context, artifactVersionID int64)) *MockRepository_ListArtifactVersionAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListArtifactVersionAssets_Call) Return(artifactVersionedAssets []db.ArtifactVersionedAsset, err error) *MockRepository_ListArtifactVersionAssets_Call {
	_c.Call.Return(artifactVersionedAssets, err)
	return _c
}

func (_c *MockRepository_ListArtifactVersionAssets_Call) RunAndReturn(run func(ctx context.Context, artifactVersionID int64) ([]db.ArtifactVersionedAsset, error)) *MockRepository_ListArtifactVersionAssets_Call {
	_c.Call.Return(run)
	return _c
}

// ListArtifactVersionTags provides a mock function for the type MockRepository
func (_mock *MockRepository) ListArtifactVersionTags(ctx context.Context, artifactVersionID int64) ([]db.ArtifactVersionedTag, error) {
	ret := _mock.Called(ctx, artifactVersionID)

	if len(ret) == 0 {
		panic("no return value specified for ListArtifactVersionTags")
	}

	var r0 []db.ArtifactVersionedTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]db.ArtifactVersionedTag, error)); ok {
		return returnFunc(ctx, artifactVersionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []db.ArtifactVersionedTag); ok {
		r0 = returnFunc(ctx, artifactVersionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ArtifactVersionedTag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, artifactVersionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListArtifactVersionTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArtifactVersionTags'
type MockRepository_ListArtifactVersionTags_Call struct {
	*mock.Call
}

// ListArtifactVersionTags is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactVersionID int64
func (_e *MockRepository_Expecter) ListArtifactVersionTags(ctx interface{}, artifactVersionID interface{}) *MockRepository_ListArtifactVersionTags_Call {
	return &MockRepository_ListArtifactVersionTags_Call{Call: _e.mock.On("ListArtifactVersionTags", ctx, artifactVersionID)}
}

func (_c *MockRepository_ListArtifactVersionTags_Call) Run(run func(ctx context.Context, artifactVersionID int64)) *MockRepository_ListArtifactVersionTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListArtifactVersionTags_Call) Return(artifactVersionedTags []db.ArtifactVersionedTag, err error) *MockRepository_ListArtifactVersionTags_Call {
	_c.Call.Return(artifactVersionedTags, err)
	return _c
}

func (_c *MockRepository_ListArtifactVersionTags_Call) RunAndReturn(run func(ctx context.Context, artifactVersionID int64) ([]db.ArtifactVersionedTag, error)) *MockRepository_ListArtifactVersionTags_Call {
	_c.Call.Return(run)
	return _c
}

// ListArtifactVersions provides a mock function for the type MockRepository
func (_mock *MockRepository) ListArtifactVersions(ctx context.Context, arg db.ListArtifactVersionsParams) ([]db.ArtifactVersion, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListArtifactVersions")
	}

	var r0 []db.ArtifactVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListArtifactVersionsParams) ([]db.ArtifactVersion, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListArtifactVersionsParams) []db.ArtifactVersion); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ArtifactVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListArtifactVersionsParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListArtifactVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArtifactVersions'
type MockRepository_ListArtifactVersions_Call struct {
	*mock.Call
}

// ListArtifactVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListArtifactVersionsParams
func (_e *MockRepository_Expecter) ListArtifactVersions(ctx interface{}, arg interface{}) *MockRepository_ListArtifactVersions_Call {
	return &MockRepository_ListArtifactVersions_Call{Call: _e.mock.On("ListArtifactVersions", ctx, arg)}
}

func (_c *MockRepository_ListArtifactVersions_Call) Run(run func(ctx context.Context, arg db.ListArtifactVersionsParams)) *MockRepository_ListArtifactVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListArtifactVersionsParams
		if args[1] != nil {
			arg1 = args[1].(db.ListArtifactVersionsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListArtifactVersions_Call) Return(artifactVersions []db.ArtifactVersion, err error) *MockRepository_ListArtifactVersions_Call {
	_c.Call.Return(artifactVersions, err)
	return _c
}

func (_c *MockRepository_ListArtifactVersions_Call) RunAndReturn(run func(ctx context.Context, arg db.ListArtifactVersionsParams) ([]db.ArtifactVersion, error)) *MockRepository_ListArtifactVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListArtifactsByGroup provides a mock function for the type MockRepository
func (_mock *MockRepository) ListArtifactsByGroup(ctx context.Context, groupID string) ([]db.Artifact, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for ListArtifactsByGroup")
	}

	var r0 []db.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]db.Artifact, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []db.Artifact); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListArtifactsByGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArtifactsByGroup'
type MockRepository_ListArtifactsByGroup_Call struct {
	*mock.Call
}

// ListArtifactsByGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
func (_e *MockRepository_Expecter) ListArtifactsByGroup(ctx interface{}, groupID interface{}) *MockRepository_ListArtifactsByGroup_Call {
	return &MockRepository_ListArtifactsByGroup_Call{Call: _e.mock.On("ListArtifactsByGroup", ctx, groupID)}
}

func (_c *MockRepository_ListArtifactsByGroup_Call) Run(run func(ctx context.Context, groupID string)) *MockRepository_ListArtifactsByGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListArtifactsByGroup_Call) Return(artifacts []db.Artifact, err error) *MockRepository_ListArtifactsByGroup_Call {
	_c.Call.Return(artifacts, err)
	return _c
}

func (_c *MockRepository_ListArtifactsByGroup_Call) RunAndReturn(run func(ctx context.Context, groupID string) ([]db.Artifact, error)) *MockRepository_ListArtifactsByGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ListGroups provides a mock function for the type MockRepository
func (_mock *MockRepository) ListGroups(ctx context.Context) ([]db.Group, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListGroups")
	}

	var r0 []db.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]db.Group, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []db.Group); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGroups'
type MockRepository_ListGroups_Call struct {
	*mock.Call
}

// ListGroups is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListGroups(ctx interface{}) *MockRepository_ListGroups_Call {
	return &MockRepository_ListGroups_Call{Call: _e.mock.On("ListGroups", ctx)}
}

func (_c *MockRepository_ListGroups_Call) Run(run func(ctx context.Context)) *MockRepository_ListGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_ListGroups_Call) Return(groups []db.Group, err error) *MockRepository_ListGroups_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockRepository_ListGroups_Call) RunAndReturn(run func(ctx context.Context) ([]db.Group, error)) *MockRepository_ListGroups_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateArtifactVersionOrder provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateArtifactVersionOrder(ctx context.Context, arg db.UpdateArtifactVersionOrderParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateArtifactVersionOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateArtifactVersionOrderParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateArtifactVersionOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateArtifactVersionOrder'
type MockRepository_UpdateArtifactVersionOrder_Call struct {
	*mock.Call
}

// UpdateArtifactVersionOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateArtifactVersionOrderParams
func (_e *MockRepository_Expecter) UpdateArtifactVersionOrder(ctx interface{}, arg interface{}) *MockRepository_UpdateArtifactVersionOrder_Call {
	return &MockRepository_UpdateArtifactVersionOrder_Call{Call: _e.mock.On("UpdateArtifactVersionOrder", ctx, arg)}
}

func (_c *MockRepository_UpdateArtifactVersionOrder_Call) Run(run func(ctx context.Context, arg db.UpdateArtifactVersionOrderParams)) *MockRepository_UpdateArtifactVersionOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.UpdateArtifactVersionOrderParams
		if args[1] != nil {
			arg1 = args[1].(db.UpdateArtifactVersionOrderParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateArtifactVersionOrder_Call) Return(err error) *MockRepository_UpdateArtifactVersionOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateArtifactVersionOrder_Call) RunAndReturn(run func(ctx context.Context, arg db.UpdateArtifactVersionOrderParams) error) *MockRepository_UpdateArtifactVersionOrder_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockRepository
func (_mock *MockRepository) WithTx(ctx context.Context, fn func(app.Repository) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(app.Repository) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(app.Repository) error
func (_e *MockRepository_Expecter) WithTx(ctx interface{}, fn interface{}) *MockRepository_WithTx_Call {
	return &MockRepository_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *MockRepository_WithTx_Call) Run(run func(ctx context.Context, fn func(app.Repository) error)) *MockRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(app.Repository) error
		if args[1] != nil {
			arg1 = args[1].(func(app.Repository) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_WithTx_Call) Return(err error) *MockRepository_WithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_WithTx_Call) RunAndReturn(run func(ctx context.Context, fn func(app.Repository) error) error) *MockRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
