// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package db

import (
	"context"

	"github.com/spongepowered/systemofadownload/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CreateArtifact provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateArtifact(ctx context.Context, arg db.CreateArtifactParams) (db.Artifact, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateArtifact")
	}

	var r0 db.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactParams) (db.Artifact, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactParams) db.Artifact); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateArtifactParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArtifact'
type MockQuerier_CreateArtifact_Call struct {
	*mock.Call
}

// CreateArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateArtifactParams
func (_e *MockQuerier_Expecter) CreateArtifact(ctx interface{}, arg interface{}) *MockQuerier_CreateArtifact_Call {
	return &MockQuerier_CreateArtifact_Call{Call: _e.mock.On("CreateArtifact", ctx, arg)}
}

func (_c *MockQuerier_CreateArtifact_Call) Run(run func(ctx context.Context, arg db.CreateArtifactParams)) *MockQuerier_CreateArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateArtifactParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateArtifactParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateArtifact_Call) Return(artifact db.Artifact, err error) *MockQuerier_CreateArtifact_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *MockQuerier_CreateArtifact_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateArtifactParams) (db.Artifact, error)) *MockQuerier_CreateArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// CreateArtifactVersion provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateArtifactVersion(ctx context.Context, arg db.CreateArtifactVersionParams) (db.ArtifactVersion, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateArtifactVersion")
	}

	var r0 db.ArtifactVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactVersionParams) (db.ArtifactVersion, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactVersionParams) db.ArtifactVersion); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ArtifactVersion)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateArtifactVersionParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateArtifactVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArtifactVersion'
type MockQuerier_CreateArtifactVersion_Call struct {
	*mock.Call
}

// CreateArtifactVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateArtifactVersionParams
func (_e *MockQuerier_Expecter) CreateArtifactVersion(ctx interface{}, arg interface{}) *MockQuerier_CreateArtifactVersion_Call {
	return &MockQuerier_CreateArtifactVersion_Call{Call: _e.mock.On("CreateArtifactVersion", ctx, arg)}
}

func (_c *MockQuerier_CreateArtifactVersion_Call) Run(run func(ctx context.Context, arg db.CreateArtifactVersionParams)) *MockQuerier_CreateArtifactVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateArtifactVersionParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateArtifactVersionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateArtifactVersion_Call) Return(artifactVersion db.ArtifactVersion, err error) *MockQuerier_CreateArtifactVersion_Call {
	_c.Call.Return(artifactVersion, err)
	return _c
}

func (_c *MockQuerier_CreateArtifactVersion_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateArtifactVersionParams) (db.ArtifactVersion, error)) *MockQuerier_CreateArtifactVersion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateArtifactVersionAsset provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateArtifactVersionAsset(ctx context.Context, arg db.CreateArtifactVersionAssetParams) (db.ArtifactVersionedAsset, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateArtifactVersionAsset")
	}

	var r0 db.ArtifactVersionedAsset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactVersionAssetParams) (db.ArtifactVersionedAsset, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactVersionAssetParams) db.ArtifactVersionedAsset); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ArtifactVersionedAsset)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateArtifactVersionAssetParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateArtifactVersionAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArtifactVersionAsset'
type MockQuerier_CreateArtifactVersionAsset_Call struct {
	*mock.Call
}

// CreateArtifactVersionAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateArtifactVersionAssetParams
func (_e *MockQuerier_Expecter) CreateArtifactVersionAsset(ctx interface{}, arg interface{}) *MockQuerier_CreateArtifactVersionAsset_Call {
	return &MockQuerier_CreateArtifactVersionAsset_Call{Call: _e.mock.On("CreateArtifactVersionAsset", ctx, arg)}
}

func (_c *MockQuerier_CreateArtifactVersionAsset_Call) Run(run func(ctx context.Context, arg db.CreateArtifactVersionAssetParams)) *MockQuerier_CreateArtifactVersionAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateArtifactVersionAssetParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateArtifactVersionAssetParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateArtifactVersionAsset_Call) Return(artifactVersionedAsset db.ArtifactVersionedAsset, err error) *MockQuerier_CreateArtifactVersionAsset_Call {
	_c.Call.Return(artifactVersionedAsset, err)
	return _c
}

func (_c *MockQuerier_CreateArtifactVersionAsset_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateArtifactVersionAssetParams) (db.ArtifactVersionedAsset, error)) *MockQuerier_CreateArtifactVersionAsset_Call {
	_c.Call.Return(run)
	return _c
}

// CreateArtifactVersionTag provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateArtifactVersionTag(ctx context.Context, arg db.CreateArtifactVersionTagParams) (db.ArtifactVersionedTag, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateArtifactVersionTag")
	}

	var r0 db.ArtifactVersionedTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactVersionTagParams) (db.ArtifactVersionedTag, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateArtifactVersionTagParams) db.ArtifactVersionedTag); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ArtifactVersionedTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateArtifactVersionTagParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateArtifactVersionTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArtifactVersionTag'
type MockQuerier_CreateArtifactVersionTag_Call struct {
	*mock.Call
}

// CreateArtifactVersionTag is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateArtifactVersionTagParams
func (_e *MockQuerier_Expecter) CreateArtifactVersionTag(ctx interface{}, arg interface{}) *MockQuerier_CreateArtifactVersionTag_Call {
	return &MockQuerier_CreateArtifactVersionTag_Call{Call: _e.mock.On("CreateArtifactVersionTag", ctx, arg)}
}

func (_c *MockQuerier_CreateArtifactVersionTag_Call) Run(run func(ctx context.Context, arg db.CreateArtifactVersionTagParams)) *MockQuerier_CreateArtifactVersionTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateArtifactVersionTagParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateArtifactVersionTagParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateArtifactVersionTag_Call) Return(artifactVersionedTag db.ArtifactVersionedTag, err error) *MockQuerier_CreateArtifactVersionTag_Call {
	_c.Call.Return(artifactVersionedTag, err)
	return _c
}

func (_c *MockQuerier_CreateArtifactVersionTag_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateArtifactVersionTagParams) (db.ArtifactVersionedTag, error)) *MockQuerier_CreateArtifactVersionTag_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroup provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateGroup(ctx context.Context, arg db.CreateGroupParams) (db.Group, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 db.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateGroupParams) (db.Group, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateGroupParams) db.Group); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Group)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateGroupParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockQuerier_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateGroupParams
func (_e *MockQuerier_Expecter) CreateGroup(ctx interface{}, arg interface{}) *MockQuerier_CreateGroup_Call {
	return &MockQuerier_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, arg)}
}

func (_c *MockQuerier_CreateGroup_Call) Run(run func(ctx context.Context, arg db.CreateGroupParams)) *MockQuerier_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateGroupParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateGroupParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateGroup_Call) Return(group db.Group, err error) *MockQuerier_CreateGroup_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockQuerier_CreateGroup_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateGroupParams) (db.Group, error)) *MockQuerier_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteArtifactVersionTags provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteArtifactVersionTags(ctx context.Context, artifactVersionID int64) error {
	ret := _mock.Called(ctx, artifactVersionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArtifactVersionTags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, artifactVersionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_DeleteArtifactVersionTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteArtifactVersionTags'
type MockQuerier_DeleteArtifactVersionTags_Call struct {
	*mock.Call
}

// DeleteArtifactVersionTags is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactVersionID int64
func (_e *MockQuerier_Expecter) DeleteArtifactVersionTags(ctx interface{}, artifactVersionID interface{}) *MockQuerier_DeleteArtifactVersionTags_Call {
	return &MockQuerier_DeleteArtifactVersionTags_Call{Call: _e.mock.On("DeleteArtifactVersionTags", ctx, artifactVersionID)}
}

func (_c *MockQuerier_DeleteArtifactVersionTags_Call) Run(run func(ctx context.Context, artifactVersionID int64)) *MockQuerier_DeleteArtifactVersionTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteArtifactVersionTags_Call) Return(err error) *MockQuerier_DeleteArtifactVersionTags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_DeleteArtifactVersionTags_Call) RunAndReturn(run func(ctx context.Context, artifactVersionID int64) error) *MockQuerier_DeleteArtifactVersionTags_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtifactByGroupAndId provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetArtifactByGroupAndId(ctx context.Context, arg db.GetArtifactByGroupAndIdParams) (db.Artifact, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactByGroupAndId")
	}

	var r0 db.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetArtifactByGroupAndIdParams) (db.Artifact, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetArtifactByGroupAndIdParams) db.Artifact); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.GetArtifactByGroupAndIdParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetArtifactByGroupAndId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtifactByGroupAndId'
type MockQuerier_GetArtifactByGroupAndId_Call struct {
	*mock.Call
}

// GetArtifactByGroupAndId is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetArtifactByGroupAndIdParams
func (_e *MockQuerier_Expecter) GetArtifactByGroupAndId(ctx interface{}, arg interface{}) *MockQuerier_GetArtifactByGroupAndId_Call {
	return &MockQuerier_GetArtifactByGroupAndId_Call{Call: _e.mock.On("GetArtifactByGroupAndId", ctx, arg)}
}

func (_c *MockQuerier_GetArtifactByGroupAndId_Call) Run(run func(ctx context.Context, arg db.GetArtifactByGroupAndIdParams)) *MockQuerier_GetArtifactByGroupAndId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.GetArtifactByGroupAndIdParams
		if args[1] != nil {
			arg1 = args[1].(db.GetArtifactByGroupAndIdParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetArtifactByGroupAndId_Call) Return(artifact db.Artifact, err error) *MockQuerier_GetArtifactByGroupAndId_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *MockQuerier_GetArtifactByGroupAndId_Call) RunAndReturn(run func(ctx context.Context, arg db.GetArtifactByGroupAndIdParams) (db.Artifact, error)) *MockQuerier_GetArtifactByGroupAndId_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtifactVersion provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetArtifactVersion(ctx context.Context, arg db.GetArtifactVersionParams) (db.ArtifactVersion, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactVersion")
	}

	var r0 db.ArtifactVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetArtifactVersionParams) (db.ArtifactVersion, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetArtifactVersionParams) db.ArtifactVersion); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ArtifactVersion)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.GetArtifactVersionParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetArtifactVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtifactVersion'
type MockQuerier_GetArtifactVersion_Call struct {
	*mock.Call
}

// GetArtifactVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetArtifactVersionParams
func (_e *MockQuerier_Expecter) GetArtifactVersion(ctx interface{}, arg interface{}) *MockQuerier_GetArtifactVersion_Call {
	return &MockQuerier_GetArtifactVersion_Call{Call: _e.mock.On("GetArtifactVersion", ctx, arg)}
}

func (_c *MockQuerier_GetArtifactVersion_Call) Run(run func(ctx context.Context, arg db.GetArtifactVersionParams)) *MockQuerier_GetArtifactVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.GetArtifactVersionParams
		if args[1] != nil {
			arg1 = args[1].(db.GetArtifactVersionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetArtifactVersion_Call) Return(artifactVersion db.ArtifactVersion, err error) *MockQuerier_GetArtifactVersion_Call {
	_c.Call.Return(artifactVersion, err)
	return _c
}

func (_c *MockQuerier_GetArtifactVersion_Call) RunAndReturn(run func(ctx context.Context, arg db.GetArtifactVersionParams) (db.ArtifactVersion, error)) *MockQuerier_GetArtifactVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtifactVersionSchema provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetArtifactVersionSchema(ctx context.Context, arg db.GetArtifactVersionSchemaParams) ([]byte, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactVersionSchema")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetArtifactVersionSchemaParams) ([]byte, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetArtifactVersionSchemaParams) []byte); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.GetArtifactVersionSchemaParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetArtifactVersionSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtifactVersionSchema'
type MockQuerier_GetArtifactVersionSchema_Call struct {
	*mock.Call
}

// GetArtifactVersionSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetArtifactVersionSchemaParams
func (_e *MockQuerier_Expecter) GetArtifactVersionSchema(ctx interface{}, arg interface{}) *MockQuerier_GetArtifactVersionSchema_Call {
	return &MockQuerier_GetArtifactVersionSchema_Call{Call: _e.mock.On("GetArtifactVersionSchema", ctx, arg)}
}

func (_c *MockQuerier_GetArtifactVersionSchema_Call) Run(run func(ctx context.Context, arg db.GetArtifactVersionSchemaParams)) *MockQuerier_GetArtifactVersionSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.GetArtifactVersionSchemaParams
		if args[1] != nil {
			arg1 = args[1].(db.GetArtifactVersionSchemaParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetArtifactVersionSchema_Call) Return(bytes []byte, err error) *MockQuerier_GetArtifactVersionSchema_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockQuerier_GetArtifactVersionSchema_Call) RunAndReturn(run func(ctx context.Context, arg db.GetArtifactVersionSchemaParams) ([]byte, error)) *MockQuerier_GetArtifactVersionSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroup provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetGroup(ctx context.Context, mavenID string) (db.Group, error) {
	ret := _mock.Called(ctx, mavenID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroup")
	}

	var r0 db.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (db.Group, error)); ok {
		return returnFunc(ctx, mavenID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) db.Group); ok {
		r0 = returnFunc(ctx, mavenID)
	} else {
		r0 = ret.Get(0).(db.Group)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, mavenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroup'
type MockQuerier_GetGroup_Call struct {
	*mock.Call
}

// GetGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - mavenID string
func (_e *MockQuerier_Expecter) GetGroup(ctx interface{}, mavenID interface{}) *MockQuerier_GetGroup_Call {
	return &MockQuerier_GetGroup_Call{Call: _e.mock.On("GetGroup", ctx, mavenID)}
}

func (_c *MockQuerier_GetGroup_Call) Run(run func(ctx context.Context, mavenID string)) *MockQuerier_GetGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetGroup_Call) Return(group db.Group, err error) *MockQuerier_GetGroup_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockQuerier_GetGroup_Call) RunAndReturn(run func(ctx context.Context, mavenID string) (db.Group, error)) *MockQuerier_GetGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GroupExistsByMavenID provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GroupExistsByMavenID(ctx context.Context, lower string) (bool, error) {
	ret := _mock.Called(ctx, lower)

	if len(ret) == 0 {
		panic("no return value specified for GroupExistsByMavenID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, lower)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, lower)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, lower)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GroupExistsByMavenID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupExistsByMavenID'
type MockQuerier_GroupExistsByMavenID_Call struct {
	*mock.Call
}

// GroupExistsByMavenID is a helper method to define mock.On call
//   - ctx context.Context
//   - lower string
func (_e *MockQuerier_Expecter) GroupExistsByMavenID(ctx interface{}, lower interface{}) *MockQuerier_GroupExistsByMavenID_Call {
	return &MockQuerier_GroupExistsByMavenID_Call{Call: _e.mock.On("GroupExistsByMavenID", ctx, lower)}
}

func (_c *MockQuerier_GroupExistsByMavenID_Call) Run(run func(ctx context.Context, lower string)) *MockQuerier_GroupExistsByMavenID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GroupExistsByMavenID_Call) Return(b bool, err error) *MockQuerier_GroupExistsByMavenID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockQuerier_GroupExistsByMavenID_Call) RunAndReturn(run func(ctx context.Context, lower string) (bool, error)) *MockQuerier_GroupExistsByMavenID_Call {
	_c.Call.Return(run)
	return _c
}

// ListArtifactVersionAssets provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListArtifactVersionAssets(ctx context.Context, artifactVersionID int64) ([]db.ArtifactVersionedAsset, error) {
	ret := _mock.Called(ctx, artifactVersionID)

	if len(ret) == 0 {
		panic("no return value specified for ListArtifactVersionAssets")
	}

	var r0 []db.ArtifactVersionedAsset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]db.ArtifactVersionedAsset, error)); ok {
		return returnFunc(ctx, artifactVersionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []db.ArtifactVersionedAsset); ok {
		r0 = returnFunc(ctx, artifactVersionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ArtifactVersionedAsset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, artifactVersionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListArtifactVersionAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArtifactVersionAssets'
type MockQuerier_ListArtifactVersionAssets_Call struct {
	*mock.Call
}

// ListArtifactVersionAssets is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactVersionID int64
func (_e *MockQuerier_Expecter) ListArtifactVersionAssets(ctx interface{}, artifactVersionID interface{}) *MockQuerier_ListArtifactVersionAssets_Call {
	return &MockQuerier_ListArtifactVersionAssets_Call{Call: _e.mock.On("ListArtifactVersionAssets", ctx, artifactVersionID)}
}

func (_c *MockQuerier_ListArtifactVersionAssets_Call) Run(run func(ctx context.Context, artifactVersionID int64)) *MockQuerier_ListArtifactVersionAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListArtifactVersionAssets_Call) Return(artifactVersionedAssets []db.ArtifactVersionedAsset, err error) *MockQuerier_ListArtifactVersionAssets_Call {
	_c.Call.Return(artifactVersionedAssets, err)
	return _c
}

func (_c *MockQuerier_ListArtifactVersionAssets_Call) RunAndReturn(run func(ctx context.Context, artifactVersionID int64) ([]db.ArtifactVersionedAsset, error)) *MockQuerier_ListArtifactVersionAssets_Call {
	_c.Call.Return(run)
	return _c
}

// ListArtifactVersionStringsByArtifactID provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListArtifactVersionStringsByArtifactID(ctx context.Context, arg db.ListArtifactVersionStringsByArtifactIDParams) ([]string, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListArtifactVersionStringsByArtifactID")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListArtifactVersionStringsByArtifactIDParams) ([]string, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListArtifactVersionStringsByArtifactIDParams) []string); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListArtifactVersionStringsByArtifactIDParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListArtifactVersionStringsByArtifactID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArtifactVersionStringsByArtifactID'
type MockQuerier_ListArtifactVersionStringsByArtifactID_Call struct {
	*mock.Call
}

// ListArtifactVersionStringsByArtifactID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListArtifactVersionStringsByArtifactIDParams
func (_e *MockQuerier_Expecter) ListArtifactVersionStringsByArtifactID(ctx interface{}, arg interface{}) *MockQuerier_ListArtifactVersionStringsByArtifactID_Call {
	return &MockQuerier_ListArtifactVersionStringsByArtifactID_Call{Call: _e.mock.On("ListArtifactVersionStringsByArtifactID", ctx, arg)}
}

func (_c *MockQuerier_ListArtifactVersionStringsByArtifactID_Call) Run(run func(ctx context.Context, arg db.ListArtifactVersionStringsByArtifactIDParams)) *MockQuerier_ListArtifactVersionStringsByArtifactID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListArtifactVersionStringsByArtifactIDParams
		if args[1] != nil {
			arg1 = args[1].(db.ListArtifactVersionStringsByArtifactIDParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListArtifactVersionStringsByArtifactID_Call) Return(strings []string, err error) *MockQuerier_ListArtifactVersionStringsByArtifactID_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockQuerier_ListArtifactVersionStringsByArtifactID_Call) RunAndReturn(run func(ctx context.Context, arg db.ListArtifactVersionStringsByArtifactIDParams) ([]string, error)) *MockQuerier_ListArtifactVersionStringsByArtifactID_Call {
	_c.Call.Return(run)
	return _c
}

// ListArtifactVersionTags provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListArtifactVersionTags(ctx context.Context, artifactVersionID int64) ([]db.ArtifactVersionedTag, error) {
	ret := _mock.Called(ctx, artifactVersionID)

	if len(ret) == 0 {
		panic("no return value specified for ListArtifactVersionTags")
	}

	var r0 []db.ArtifactVersionedTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]db.ArtifactVersionedTag, error)); ok {
		return returnFunc(ctx, artifactVersionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []db.ArtifactVersionedTag); ok {
		r0 = returnFunc(ctx, artifactVersionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ArtifactVersionedTag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, artifactVersionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListArtifactVersionTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArtifactVersionTags'
type MockQuerier_ListArtifactVersionTags_Call struct {
	*mock.Call
}

// ListArtifactVersionTags is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactVersionID int64
func (_e *MockQuerier_Expecter) ListArtifactVersionTags(ctx interface{}, artifactVersionID interface{}) *MockQuerier_ListArtifactVersionTags_Call {
	return &MockQuerier_ListArtifactVersionTags_Call{Call: _e.mock.On("ListArtifactVersionTags", ctx, artifactVersionID)}
}

func (_c *MockQuerier_ListArtifactVersionTags_Call) Run(run func(ctx context.Context, artifactVersionID int64)) *MockQuerier_ListArtifactVersionTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListArtifactVersionTags_Call) Return(artifactVersionedTags []db.ArtifactVersionedTag, err error) *MockQuerier_ListArtifactVersionTags_Call {
	_c.Call.Return(artifactVersionedTags, err)
	return _c
}

func (_c *MockQuerier_ListArtifactVersionTags_Call) RunAndReturn(run func(ctx context.Context, artifactVersionID int64) ([]db.ArtifactVersionedTag, error)) *MockQuerier_ListArtifactVersionTags_Call {
	_c.Call.Return(run)
	return _c
}

// ListArtifactVersions provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListArtifactVersions(ctx context.Context, arg db.ListArtifactVersionsParams) ([]db.ArtifactVersion, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListArtifactVersions")
	}

	var r0 []db.ArtifactVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListArtifactVersionsParams) ([]db.ArtifactVersion, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListArtifactVersionsParams) []db.ArtifactVersion); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ArtifactVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListArtifactVersionsParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListArtifactVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArtifactVersions'
type MockQuerier_ListArtifactVersions_Call struct {
	*mock.Call
}

// ListArtifactVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListArtifactVersionsParams
func (_e *MockQuerier_Expecter) ListArtifactVersions(ctx interface{}, arg interface{}) *MockQuerier_ListArtifactVersions_Call {
	return &MockQuerier_ListArtifactVersions_Call{Call: _e.mock.On("ListArtifactVersions", ctx, arg)}
}

func (_c *MockQuerier_ListArtifactVersions_Call) Run(run func(ctx context.Context, arg db.ListArtifactVersionsParams)) *MockQuerier_ListArtifactVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListArtifactVersionsParams
		if args[1] != nil {
			arg1 = args[1].(db.ListArtifactVersionsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListArtifactVersions_Call) Return(artifactVersions []db.ArtifactVersion, err error) *MockQuerier_ListArtifactVersions_Call {
	_c.Call.Return(artifactVersions, err)
	return _c
}

func (_c *MockQuerier_ListArtifactVersions_Call) RunAndReturn(run func(ctx context.Context, arg db.ListArtifactVersionsParams) ([]db.ArtifactVersion, error)) *MockQuerier_ListArtifactVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListArtifactsByGroup provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListArtifactsByGroup(ctx context.Context, groupID string) ([]db.Artifact, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for ListArtifactsByGroup")
	}

	var r0 []db.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]db.Artifact, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []db.Artifact); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListArtifactsByGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArtifactsByGroup'
type MockQuerier_ListArtifactsByGroup_Call struct {
	*mock.Call
}

// ListArtifactsByGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
func (_e *MockQuerier_Expecter) ListArtifactsByGroup(ctx interface{}, groupID interface{}) *MockQuerier_ListArtifactsByGroup_Call {
	return &MockQuerier_ListArtifactsByGroup_Call{Call: _e.mock.On("ListArtifactsByGroup", ctx, groupID)}
}

func (_c *MockQuerier_ListArtifactsByGroup_Call) Run(run func(ctx context.Context, groupID string)) *MockQuerier_ListArtifactsByGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListArtifactsByGroup_Call) Return(artifacts []db.Artifact, err error) *MockQuerier_ListArtifactsByGroup_Call {
	_c.Call.Return(artifacts, err)
	return _c
}

func (_c *MockQuerier_ListArtifactsByGroup_Call) RunAndReturn(run func(ctx context.Context, groupID string) ([]db.Artifact, error)) *MockQuerier_ListArtifactsByGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ListDistinctTagsByArtifact provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListDistinctTagsByArtifact(ctx context.Context, arg db.ListDistinctTagsByArtifactParams) ([]db.ListDistinctTagsByArtifactRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListDistinctTagsByArtifact")
	}

	var r0 []db.ListDistinctTagsByArtifactRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListDistinctTagsByArtifactParams) ([]db.ListDistinctTagsByArtifactRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListDistinctTagsByArtifactParams) []db.ListDistinctTagsByArtifactRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ListDistinctTagsByArtifactRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListDistinctTagsByArtifactParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListDistinctTagsByArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDistinctTagsByArtifact'
type MockQuerier_ListDistinctTagsByArtifact_Call struct {
	*mock.Call
}

// ListDistinctTagsByArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListDistinctTagsByArtifactParams
func (_e *MockQuerier_Expecter) ListDistinctTagsByArtifact(ctx interface{}, arg interface{}) *MockQuerier_ListDistinctTagsByArtifact_Call {
	return &MockQuerier_ListDistinctTagsByArtifact_Call{Call: _e.mock.On("ListDistinctTagsByArtifact", ctx, arg)}
}

func (_c *MockQuerier_ListDistinctTagsByArtifact_Call) Run(run func(ctx context.Context, arg db.ListDistinctTagsByArtifactParams)) *MockQuerier_ListDistinctTagsByArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListDistinctTagsByArtifactParams
		if args[1] != nil {
			arg1 = args[1].(db.ListDistinctTagsByArtifactParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListDistinctTagsByArtifact_Call) Return(listDistinctTagsByArtifactRows []db.ListDistinctTagsByArtifactRow, err error) *MockQuerier_ListDistinctTagsByArtifact_Call {
	_c.Call.Return(listDistinctTagsByArtifactRows, err)
	return _c
}

func (_c *MockQuerier_ListDistinctTagsByArtifact_Call) RunAndReturn(run func(ctx context.Context, arg db.ListDistinctTagsByArtifactParams) ([]db.ListDistinctTagsByArtifactRow, error)) *MockQuerier_ListDistinctTagsByArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// ListGroups provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListGroups(ctx context.Context) ([]db.Group, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListGroups")
	}

	var r0 []db.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]db.Group, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []db.Group); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGroups'
type MockQuerier_ListGroups_Call struct {
	*mock.Call
}

// ListGroups is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) ListGroups(ctx interface{}) *MockQuerier_ListGroups_Call {
	return &MockQuerier_ListGroups_Call{Call: _e.mock.On("ListGroups", ctx)}
}

func (_c *MockQuerier_ListGroups_Call) Run(run func(ctx context.Context)) *MockQuerier_ListGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuerier_ListGroups_Call) Return(groups []db.Group, err error) *MockQuerier_ListGroups_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockQuerier_ListGroups_Call) RunAndReturn(run func(ctx context.Context) ([]db.Group, error)) *MockQuerier_ListGroups_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateArtifactVersionCommitBody provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateArtifactVersionCommitBody(ctx context.Context, arg db.UpdateArtifactVersionCommitBodyParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateArtifactVersionCommitBody")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateArtifactVersionCommitBodyParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_UpdateArtifactVersionCommitBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateArtifactVersionCommitBody'
type MockQuerier_UpdateArtifactVersionCommitBody_Call struct {
	*mock.Call
}

// UpdateArtifactVersionCommitBody is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateArtifactVersionCommitBodyParams
func (_e *MockQuerier_Expecter) UpdateArtifactVersionCommitBody(ctx interface{}, arg interface{}) *MockQuerier_UpdateArtifactVersionCommitBody_Call {
	return &MockQuerier_UpdateArtifactVersionCommitBody_Call{Call: _e.mock.On("UpdateArtifactVersionCommitBody", ctx, arg)}
}

func (_c *MockQuerier_UpdateArtifactVersionCommitBody_Call) Run(run func(ctx context.Context, arg db.UpdateArtifactVersionCommitBodyParams)) *MockQuerier_UpdateArtifactVersionCommitBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.UpdateArtifactVersionCommitBodyParams
		if args[1] != nil {
			arg1 = args[1].(db.UpdateArtifactVersionCommitBodyParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateArtifactVersionCommitBody_Call) Return(err error) *MockQuerier_UpdateArtifactVersionCommitBody_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_UpdateArtifactVersionCommitBody_Call) RunAndReturn(run func(ctx context.Context, arg db.UpdateArtifactVersionCommitBodyParams) error) *MockQuerier_UpdateArtifactVersionCommitBody_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateArtifactVersionOrder provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateArtifactVersionOrder(ctx context.Context, arg db.UpdateArtifactVersionOrderParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateArtifactVersionOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateArtifactVersionOrderParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_UpdateArtifactVersionOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateArtifactVersionOrder'
type MockQuerier_UpdateArtifactVersionOrder_Call struct {
	*mock.Call
}

// UpdateArtifactVersionOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateArtifactVersionOrderParams
func (_e *MockQuerier_Expecter) UpdateArtifactVersionOrder(ctx interface{}, arg interface{}) *MockQuerier_UpdateArtifactVersionOrder_Call {
	return &MockQuerier_UpdateArtifactVersionOrder_Call{Call: _e.mock.On("UpdateArtifactVersionOrder", ctx, arg)}
}

func (_c *MockQuerier_UpdateArtifactVersionOrder_Call) Run(run func(ctx context.Context, arg db.UpdateArtifactVersionOrderParams)) *MockQuerier_UpdateArtifactVersionOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.UpdateArtifactVersionOrderParams
		if args[1] != nil {
			arg1 = args[1].(db.UpdateArtifactVersionOrderParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateArtifactVersionOrder_Call) Return(err error) *MockQuerier_UpdateArtifactVersionOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_UpdateArtifactVersionOrder_Call) RunAndReturn(run func(ctx context.Context, arg db.UpdateArtifactVersionOrderParams) error) *MockQuerier_UpdateArtifactVersionOrder_Call {
	_c.Call.Return(run)
	return _c
}
