//go:build integration

package gitcache

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
)

var updateGolden = flag.Bool("update", false, "regenerate golden files from shell backend")

const goldenDir = "testdata"

const (
	repoSponge        = "https://github.com/SpongePowered/Sponge"
	repoSpongeForge   = "https://github.com/SpongePowered/SpongeForge"
	repoSpongeVanilla = "https://github.com/SpongePowered/SpongeVanilla"
)

// goldenSnapshot captures the output of GetCommitDetails and ResolveSubmodules
// for a single commit SHA. Generated by the shell backend (-update), then used
// to verify go-git produces identical results.
type goldenSnapshot struct {
	Commit     *CommitDetails `json:"commit"`
	Submodules []SubmoduleRef `json:"submodules"`
}

type corpusEntry struct {
	SHA  string
	Repo string
	Tag  string // human-readable label for test output
}

// integrationCorpus is the pinned set of SHAs for golden file testing.
// 10 hand-picked (5 merge commits + edge cases) + 37 randomly sampled from
// staging DB, stratified by repo. Do not re-randomize.
//
// To regenerate golden files after an intentional change:
//
//	go test -tags integration -run TestIntegrationGolden -update ./internal/gitcache/
var integrationCorpus = []corpusEntry{
	// ── Hand-picked: merge commits (5 confirmed 2-parent merges) ─────────
	{SHA: "d9f92c89c04def77f80f17c247a545b41d4de900", Repo: repoSponge, Tag: "merge-large-8426"},
	{SHA: "61ea292e0c2e131bef6213ce2b97f9b8dee8048e", Repo: repoSponge, Tag: "merge-large-2768"},
	{SHA: "ba60aa5e3bed0a2cc9a90049ef90756d1c99d261", Repo: repoSponge, Tag: "merge-large-2704"},
	{SHA: "1265b3d2bafd8b1f595664923a8c7cb28d083c52", Repo: repoSponge, Tag: "merge-small"},
	{SHA: "ffa73960f874dd5592e0e159d07fa2d80450afbe", Repo: repoSponge, Tag: "merge-medium"},

	// ── Hand-picked: edge cases ──────────────────────────────────────────
	{SHA: "6e48bc875aaa29e2ce27a195c781686a161d872c", Repo: repoSponge, Tag: "unicode-author"},
	{SHA: "aadb163c6e50062dde0d16beab619da275c12d8c", Repo: repoSponge, Tag: "small-commit-731"},
	{SHA: "1fa46c1664fad2b9973d49dd8e19c09d0904ddff", Repo: repoSpongeVanilla, Tag: "large-body-vanilla-8220"},
	{SHA: "000fa6fc9d2ac71e635c21eb8c5ff4380f4e28ac", Repo: repoSponge, Tag: "empty-body"},
	{SHA: "dfa2a385f684ddb13e450f10a34c4121c1e44922", Repo: repoSpongeForge, Tag: "long-body-1825"},
	{SHA: "0fb00f46f8af40790d7d9f23600e4000073a6886", Repo: repoSpongeForge, Tag: "long-body-1112"},

	// ── Random sample: Sponge (17) ───────────────────────────────────────
	{SHA: "e22865053acc310a44ce71b199db50b8bed119e3", Repo: repoSponge, Tag: "random"},
	{SHA: "f3c53937d9ff0c0e2966401889a045e7a8ad532f", Repo: repoSponge, Tag: "random"},
	{SHA: "0fae3f816b51b98fc3960b3934eeea7d9d9b2fae", Repo: repoSponge, Tag: "random"},
	{SHA: "9166694ba7b67dbd337749ddca8c84212d1869a7", Repo: repoSponge, Tag: "random"},
	{SHA: "1a07c8baa7b3459277b2a26e0b23b20fd4784872", Repo: repoSponge, Tag: "random"},
	{SHA: "ecfb45a07750d7c4cbf452e2bfb328b6f3ab06d6", Repo: repoSponge, Tag: "random"},
	{SHA: "2b2cadd489e27cd18395874ac81ef6cee35f4a22", Repo: repoSponge, Tag: "random"},
	{SHA: "0a75cbc68804fc16f1f8fb9c636dbb54ca4846fa", Repo: repoSponge, Tag: "random"},
	{SHA: "a5199c40b0b893d6060439c80ec0dd89df731da2", Repo: repoSponge, Tag: "random"},
	{SHA: "8b4cf4e28e95e4a5034bdf4ebdb1f1f5f47e9ed0", Repo: repoSponge, Tag: "random"},
	{SHA: "93e0bc4218797f9e180333584e0948a5c5c37b1e", Repo: repoSponge, Tag: "random"},
	{SHA: "af13f44581ad91be1fcc23877049118a31ee7f5b", Repo: repoSponge, Tag: "random"},
	{SHA: "08a827e50de8f621c0229c5838be6cf6d9915205", Repo: repoSponge, Tag: "random"},
	{SHA: "5d39e239d8de5e746efdb82725854ee1f57a34a5", Repo: repoSponge, Tag: "random"},
	{SHA: "80f2141eb8644dfbd108dd9c7bc5b0da56f9db41", Repo: repoSponge, Tag: "random"},
	{SHA: "b4e5748c3001718ca30a2dc34e6a1408ed11a560", Repo: repoSponge, Tag: "random"},
	{SHA: "1f064789464c08c826fc9e54922cd5a709703cd4", Repo: repoSponge, Tag: "random"},

	// ── Random sample: SpongeForge (12) ──────────────────────────────────
	{SHA: "04b0951c4b115ecef63957baa21686187a65cbc0", Repo: repoSpongeForge, Tag: "random"},
	{SHA: "a8e538caba756286fffbc2ac39572cd658db8510", Repo: repoSpongeForge, Tag: "random"},
	{SHA: "8e1c9298fa70b04eabf5fcbb76d36454bee9fa9b", Repo: repoSpongeForge, Tag: "random"},
	{SHA: "1fcb7eb0ce317c53a71806bf8141d8a060a50764", Repo: repoSpongeForge, Tag: "random"},
	{SHA: "ee6045f2133a02b7663cf89c974c95e5fcefc0b0", Repo: repoSpongeForge, Tag: "random"},
	{SHA: "bb230f1bbf405f8c4977bf9f6ae0261414021b76", Repo: repoSpongeForge, Tag: "random"},
	{SHA: "081bd3fb20ca5dd1769465ab493b6e0a1bb480f0", Repo: repoSpongeForge, Tag: "random"},
	{SHA: "7d1823d0a2d6dd09a351273b94e222eaab8dcad8", Repo: repoSpongeForge, Tag: "random"},
	{SHA: "0048a2d8556f593478735a9060b953df6161f066", Repo: repoSpongeForge, Tag: "random"},
	{SHA: "4bccb658603343c555d110a84b2d24189a2c6c8c", Repo: repoSpongeForge, Tag: "random"},
	{SHA: "63772bd586a35a4d8f39af30199deda02b62714e", Repo: repoSpongeForge, Tag: "random"},
	{SHA: "230cd9b6254105de8f76d45d1125070c162313e6", Repo: repoSpongeForge, Tag: "random"},

	// ── Random sample: SpongeVanilla (6) ─────────────────────────────────
	{SHA: "222b0406ebf0e168057ec5aafad9bffff2025b3a", Repo: repoSpongeVanilla, Tag: "random"},
	{SHA: "dbd149afbb999fb1e919f687c36bca734e9a3af7", Repo: repoSpongeVanilla, Tag: "random"},
	{SHA: "b8d97aba5486e51e3ad7175ceabc9840bc7c7f12", Repo: repoSpongeVanilla, Tag: "random"},
	{SHA: "f2f737bb9275448e6b4b29860c50b83067a48a35", Repo: repoSpongeVanilla, Tag: "random"},
	{SHA: "89ffcb26858bb9c7a6382b543753416e6e3f1b8b", Repo: repoSpongeVanilla, Tag: "random"},
	{SHA: "2ecde63673a5602f38a5f1615c25362cbad9e5c7", Repo: repoSpongeVanilla, Tag: "random"},
}

func TestIntegrationGolden(t *testing.T) {
	ctx := t.Context()
	cacheDir := t.TempDir()

	// In -update mode the shell backend is the source of truth.
	// In normal mode the go-git backend is tested against the golden files.
	var reader RepoReader
	if *updateGolden {
		reader = NewManager(cacheDir)
		if err := os.MkdirAll(goldenDir, 0o755); err != nil {
			t.Fatal(err)
		}
	} else {
		reader = NewGoGitReader(NewManager(cacheDir))
	}

	// Clone each unique repo once. This is the slow part (network I/O).
	handles := make(map[string]string) // repo URL → handle
	for _, e := range integrationCorpus {
		if _, ok := handles[e.Repo]; ok {
			continue
		}
		t.Logf("cloning %s ...", e.Repo)
		handle, err := reader.EnsureCloned(ctx, e.Repo)
		if err != nil {
			t.Fatalf("EnsureCloned(%s): %v", e.Repo, err)
		}
		handles[e.Repo] = handle
	}

	for _, e := range integrationCorpus {

		name := fmt.Sprintf("%s/%s", e.SHA[:12], e.Tag)
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			handle := handles[e.Repo]

			commit, err := reader.GetCommitDetails(ctx, handle, e.SHA)
			if err != nil {
				t.Fatalf("GetCommitDetails(%s): %v", e.SHA[:12], err)
			}

			submodules, err := reader.ResolveSubmodules(ctx, handle, e.SHA)
			if err != nil {
				t.Fatalf("ResolveSubmodules(%s): %v", e.SHA[:12], err)
			}

			actual := goldenSnapshot{
				Commit:     commit,
				Submodules: submodules,
			}

			goldenFile := filepath.Join(goldenDir, e.SHA+".json")

			if *updateGolden {
				writeGolden(t, goldenFile, &actual)
				return
			}

			want := readGolden(t, goldenFile)
			if diff := cmp.Diff(want, actual, normalizeUTCDate); diff != "" {
				t.Errorf("mismatch vs golden (-golden +go-git):\n%s", diff)
			}
		})
	}
}

// writeGolden normalizes UTC dates for cross-platform consistency, then writes
// the snapshot as indented JSON.
func writeGolden(t *testing.T, path string, s *goldenSnapshot) {
	t.Helper()
	// Normalize "Z" → "+00:00" so golden files are deterministic regardless
	// of the platform git %aI behavior (Linux emits Z, macOS emits +00:00).
	if s.Commit != nil {
		s.Commit.CommitDate = normalizeUTCInDate(s.Commit.CommitDate)
	}
	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, append(data, '\n'), 0o644); err != nil { //nolint:gosec // test golden files
		t.Fatal(err)
	}
	t.Logf("wrote %s", path)
}

func readGolden(t *testing.T, path string) goldenSnapshot {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading golden file: %v\n(run with -update to generate)", err)
	}
	var s goldenSnapshot
	if err := json.Unmarshal(data, &s); err != nil {
		t.Fatalf("parsing golden file %s: %v", filepath.Base(path), err)
	}
	return s
}

// normalizeUTCInDate converts a trailing "Z" to "+00:00" for date strings.
func normalizeUTCInDate(d string) string {
	if strings.HasSuffix(d, "Z") {
		return d[:len(d)-1] + "+00:00"
	}
	return d
}
