// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sonatype

import (
	"context"

	"github.com/spongepowered/systemofadownload/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// FetchVersions provides a mock function for the type MockClient
func (_mock *MockClient) FetchVersions(ctx context.Context, groupID string, artifactID string) ([]domain.VersionInfo, error) {
	ret := _mock.Called(ctx, groupID, artifactID)

	if len(ret) == 0 {
		panic("no return value specified for FetchVersions")
	}

	var r0 []domain.VersionInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.VersionInfo, error)); ok {
		return returnFunc(ctx, groupID, artifactID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []domain.VersionInfo); ok {
		r0 = returnFunc(ctx, groupID, artifactID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.VersionInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, groupID, artifactID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_FetchVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchVersions'
type MockClient_FetchVersions_Call struct {
	*mock.Call
}

// FetchVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID string
//   - artifactID string
func (_e *MockClient_Expecter) FetchVersions(ctx interface{}, groupID interface{}, artifactID interface{}) *MockClient_FetchVersions_Call {
	return &MockClient_FetchVersions_Call{Call: _e.mock.On("FetchVersions", ctx, groupID, artifactID)}
}

func (_c *MockClient_FetchVersions_Call) Run(run func(ctx context.Context, groupID string, artifactID string)) *MockClient_FetchVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_FetchVersions_Call) Return(versionInfos []domain.VersionInfo, err error) *MockClient_FetchVersions_Call {
	_c.Call.Return(versionInfos, err)
	return _c
}

func (_c *MockClient_FetchVersions_Call) RunAndReturn(run func(ctx context.Context, groupID string, artifactID string) ([]domain.VersionInfo, error)) *MockClient_FetchVersions_Call {
	_c.Call.Return(run)
	return _c
}
