
micronaut:
  data:
    enabled: true
  serde:
    enabled: true
  jackson:
    enabled: true
  executors:
    git-resolver:
      core-pool-size: 2
      max-pool-size: 10
      keep-alive-time: 30s
      queue-size: 1000
      thread-factory: git-resolver
datasources:
  default:
    db-type: postgresql
    dialect: POSTGRES
    driver: postgresql
    options:
      currentSchema: artifact
    pool:
      max-size: 10
      max-idle-time: 30m
    driver-class-name: org.postgresql.Driver

liquibase:
  enabled: true
  datasources:
    default:
      enabled: true
      change-log: 'classpath:db/liquibase-changelog.xml' # (4)
