
micronaut:
  data:
    enabled: true
  executors:
    git-resolver:
      core-pool-size: 2
      max-pool-size: 10
      keep-alive-time: 30s
      queue-size: 1000
      thread-factory: git-resolver
