micronaut.application.name = 'artifacts'
netty.default.allocator.max-order = 3

[r2dbc.datasources.default]
schema-generate = 'CREATE_DROP'
dialect = 'H2'

[micronaut.security]
authentication = 'bearer'
token.jwt.signatures.secret.generator.secret = '${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}'
