// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package httpapi

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/sdk/client"
)

// NewMockWorkflowStarter creates a new instance of MockWorkflowStarter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflowStarter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflowStarter {
	mock := &MockWorkflowStarter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkflowStarter is an autogenerated mock type for the WorkflowStarter type
type MockWorkflowStarter struct {
	mock.Mock
}

type MockWorkflowStarter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflowStarter) EXPECT() *MockWorkflowStarter_Expecter {
	return &MockWorkflowStarter_Expecter{mock: &_m.Mock}
}

// ExecuteWorkflow provides a mock function for the type MockWorkflowStarter
func (_mock *MockWorkflowStarter) ExecuteWorkflow(ctx context.Context, options client.StartWorkflowOptions, workflow interface{}, args ...interface{}) (client.WorkflowRun, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, options, workflow)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteWorkflow")
	}

	var r0 client.WorkflowRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.StartWorkflowOptions, interface{}, ...interface{}) (client.WorkflowRun, error)); ok {
		return returnFunc(ctx, options, workflow, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.StartWorkflowOptions, interface{}, ...interface{}) client.WorkflowRun); ok {
		r0 = returnFunc(ctx, options, workflow, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.WorkflowRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.StartWorkflowOptions, interface{}, ...interface{}) error); ok {
		r1 = returnFunc(ctx, options, workflow, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkflowStarter_ExecuteWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteWorkflow'
type MockWorkflowStarter_ExecuteWorkflow_Call struct {
	*mock.Call
}

// ExecuteWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - options client.StartWorkflowOptions
//   - workflow interface{}
//   - args ...interface{}
func (_e *MockWorkflowStarter_Expecter) ExecuteWorkflow(ctx interface{}, options interface{}, workflow interface{}, args ...interface{}) *MockWorkflowStarter_ExecuteWorkflow_Call {
	return &MockWorkflowStarter_ExecuteWorkflow_Call{Call: _e.mock.On("ExecuteWorkflow",
		append([]interface{}{ctx, options, workflow}, args...)...)}
}

func (_c *MockWorkflowStarter_ExecuteWorkflow_Call) Run(run func(ctx context.Context, options client.StartWorkflowOptions, workflow interface{}, args ...interface{})) *MockWorkflowStarter_ExecuteWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.StartWorkflowOptions
		if args[1] != nil {
			arg1 = args[1].(client.StartWorkflowOptions)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []interface{}
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockWorkflowStarter_ExecuteWorkflow_Call) Return(v client.WorkflowRun, err error) *MockWorkflowStarter_ExecuteWorkflow_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWorkflowStarter_ExecuteWorkflow_Call) RunAndReturn(run func(ctx context.Context, options client.StartWorkflowOptions, workflow interface{}, args ...interface{}) (client.WorkflowRun, error)) *MockWorkflowStarter_ExecuteWorkflow_Call {
	_c.Call.Return(run)
	return _c
}
