// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artifact struct {
	ID              int64
	GroupID         string
	ArtifactID      string
	Name            string
	Website         *string
	Issues          *string
	GitRepositories []byte
	VersionSchema   []byte
}

type ArtifactVersion struct {
	ID          int64
	ArtifactID  int64
	Version     string
	SortOrder   int32
	Recommended bool
	CommitBody  []byte
}

type ArtifactVersionedAsset struct {
	ID                int64
	ArtifactVersionID int64
	Classifier        *string
	Sha256            *string
	DownloadUrl       string
	Md5               *string
	Sha1              *string
	Sha512            *string
	Extension         *string
}

type ArtifactVersionedTag struct {
	ArtifactVersionID int64
	TagKey            string
	TagValue          string
}

type GithubUserCache struct {
	AuthorEmail    string
	GithubUsername *string
	ExpiresAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Group struct {
	MavenID string
	Name    string
	Website *string
}
