// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error)
	CreateArtifactVersion(ctx context.Context, arg CreateArtifactVersionParams) (ArtifactVersion, error)
	CreateArtifactVersionAsset(ctx context.Context, arg CreateArtifactVersionAssetParams) (ArtifactVersionedAsset, error)
	CreateArtifactVersionTag(ctx context.Context, arg CreateArtifactVersionTagParams) (ArtifactVersionedTag, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	GetArtifactByGroupAndId(ctx context.Context, arg GetArtifactByGroupAndIdParams) (Artifact, error)
	GetArtifactVersion(ctx context.Context, arg GetArtifactVersionParams) (ArtifactVersion, error)
	GetGroup(ctx context.Context, mavenID string) (Group, error)
	GroupExistsByMavenID(ctx context.Context, lower string) (bool, error)
	ListArtifactVersionAssets(ctx context.Context, artifactVersionID int64) ([]ArtifactVersionedAsset, error)
	ListArtifactVersionTags(ctx context.Context, artifactVersionID int64) ([]ArtifactVersionedTag, error)
	ListArtifactVersions(ctx context.Context, arg ListArtifactVersionsParams) ([]ArtifactVersion, error)
	ListArtifactsByGroup(ctx context.Context, groupID string) ([]Artifact, error)
	ListGroups(ctx context.Context) ([]Group, error)
	UpdateArtifactVersionOrder(ctx context.Context, arg UpdateArtifactVersionOrderParams) error
}

var _ Querier = (*Queries)(nil)
