// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountArtifactVersions(ctx context.Context, arg CountArtifactVersionsParams) (int32, error)
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error)
	// Upserts an artifact version. On conflict, sort_order is always refreshed
	// while commit_body is merged defensively so that concurrent writers from
	// different stages of the pipeline (initial indexing, enrichment, self-repair)
	// do not clobber each other. Rules, in order:
	//   1. If the incoming payload is null, keep the existing row.
	//   2. If the existing row is null, take the incoming payload wholesale.
	//   3. If the incoming payload has no usable sha but the existing row does,
	//      keep the existing row — a shallow re-index must not overwrite a good
	//      sha with an empty one (prevents concurrent-sync-vs-repair races).
	//   4. Otherwise, shallow-merge JSONB with the incoming payload winning on
	//      overlapping keys. This preserves enrichment-only fields (body, author,
	//      changelog, submodules, enrichedAt, ...) when a shallower write arrives.
	CreateArtifactVersion(ctx context.Context, arg CreateArtifactVersionParams) (ArtifactVersion, error)
	CreateArtifactVersionAsset(ctx context.Context, arg CreateArtifactVersionAssetParams) (ArtifactVersionedAsset, error)
	CreateArtifactVersionTag(ctx context.Context, arg CreateArtifactVersionTagParams) (ArtifactVersionedTag, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	DeleteArtifactVersionAssets(ctx context.Context, artifactVersionID int64) error
	DeleteArtifactVersionTags(ctx context.Context, artifactVersionID int64) error
	GetArtifactByGroupAndId(ctx context.Context, arg GetArtifactByGroupAndIdParams) (Artifact, error)
	GetArtifactVersion(ctx context.Context, arg GetArtifactVersionParams) (ArtifactVersion, error)
	GetArtifactVersionByID(ctx context.Context, id int64) (ArtifactVersion, error)
	GetArtifactVersionSchema(ctx context.Context, arg GetArtifactVersionSchemaParams) ([]byte, error)
	GetGroup(ctx context.Context, mavenID string) (Group, error)
	GetPreviousVersion(ctx context.Context, arg GetPreviousVersionParams) (ArtifactVersion, error)
	GroupExistsByMavenID(ctx context.Context, lower string) (bool, error)
	IsVersionEnriched(ctx context.Context, id int64) (bool, error)
	ListArtifactVersionAssets(ctx context.Context, artifactVersionID int64) ([]ArtifactVersionedAsset, error)
	ListArtifactVersionStringsByArtifactID(ctx context.Context, arg ListArtifactVersionStringsByArtifactIDParams) ([]string, error)
	ListArtifactVersionTags(ctx context.Context, artifactVersionID int64) ([]ArtifactVersionedTag, error)
	ListArtifactVersions(ctx context.Context, arg ListArtifactVersionsParams) ([]ArtifactVersion, error)
	ListArtifactVersionsPaginated(ctx context.Context, arg ListArtifactVersionsPaginatedParams) ([]ArtifactVersion, error)
	ListArtifactsByGroup(ctx context.Context, groupID string) ([]Artifact, error)
	ListDistinctTagsByArtifact(ctx context.Context, arg ListDistinctTagsByArtifactParams) ([]ListDistinctTagsByArtifactRow, error)
	ListGroups(ctx context.Context) ([]Group, error)
	ListTagsForVersions(ctx context.Context, dollar_1 []int64) ([]ArtifactVersionedTag, error)
	ListVersionsNeedingChangelog(ctx context.Context, arg ListVersionsNeedingChangelogParams) ([]ArtifactVersion, error)
	ListVersionsNeedingEnrichment(ctx context.Context, arg ListVersionsNeedingEnrichmentParams) ([]ArtifactVersion, error)
	UpdateArtifactFields(ctx context.Context, arg UpdateArtifactFieldsParams) (Artifact, error)
	UpdateArtifactVersionCommitBody(ctx context.Context, arg UpdateArtifactVersionCommitBodyParams) error
	UpdateArtifactVersionOrder(ctx context.Context, arg UpdateArtifactVersionOrderParams) error
	UpdateArtifactVersionSchema(ctx context.Context, arg UpdateArtifactVersionSchemaParams) error
}

var _ Querier = (*Queries)(nil)
