// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const countArtifactVersions = `-- name: CountArtifactVersions :one
SELECT COUNT(*)::int FROM artifact_versions av
JOIN artifacts a ON av.artifact_id = a.id
WHERE a.group_id = $1 AND a.artifact_id = $2
  AND ($3::boolean IS NULL OR av.recommended = $3)
`

type CountArtifactVersionsParams struct {
	GroupID     string
	ArtifactID  string
	Recommended *bool
}

func (q *Queries) CountArtifactVersions(ctx context.Context, arg CountArtifactVersionsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countArtifactVersions, arg.GroupID, arg.ArtifactID, arg.Recommended)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (group_id, artifact_id, name, website, issues, git_repositories, version_schema)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (group_id, artifact_id) DO UPDATE SET
    name = EXCLUDED.name,
    website = EXCLUDED.website,
    issues = EXCLUDED.issues,
    git_repositories = EXCLUDED.git_repositories,
    version_schema = EXCLUDED.version_schema
RETURNING id, group_id, artifact_id, name, website, issues, git_repositories, version_schema
`

type CreateArtifactParams struct {
	GroupID         string
	ArtifactID      string
	Name            string
	Website         *string
	Issues          *string
	GitRepositories []byte
	VersionSchema   []byte
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.GroupID,
		arg.ArtifactID,
		arg.Name,
		arg.Website,
		arg.Issues,
		arg.GitRepositories,
		arg.VersionSchema,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ArtifactID,
		&i.Name,
		&i.Website,
		&i.Issues,
		&i.GitRepositories,
		&i.VersionSchema,
	)
	return i, err
}

const createArtifactVersion = `-- name: CreateArtifactVersion :one
INSERT INTO artifact_versions (artifact_id, version, sort_order, commit_body)
VALUES ($1, $2, $3, $4)
ON CONFLICT (artifact_id, version) DO UPDATE SET
    sort_order = EXCLUDED.sort_order,
    commit_body = CASE
        WHEN EXCLUDED.commit_body IS NULL THEN artifact_versions.commit_body
        WHEN artifact_versions.commit_body IS NULL THEN EXCLUDED.commit_body
        WHEN (EXCLUDED.commit_body->>'sha' IS NULL OR EXCLUDED.commit_body->>'sha' = '')
             AND (artifact_versions.commit_body->>'sha' IS NOT NULL
                  AND artifact_versions.commit_body->>'sha' <> '')
            THEN artifact_versions.commit_body
        ELSE artifact_versions.commit_body || EXCLUDED.commit_body
    END
RETURNING id, artifact_id, version, sort_order, recommended, commit_body
`

type CreateArtifactVersionParams struct {
	ArtifactID int64
	Version    string
	SortOrder  int32
	CommitBody []byte
}

// Upserts an artifact version. On conflict, sort_order is always refreshed
// while commit_body is merged defensively so that concurrent writers from
// different stages of the pipeline (initial indexing, enrichment, self-repair)
// do not clobber each other. Rules, in order:
//  1. If the incoming payload is null, keep the existing row.
//  2. If the existing row is null, take the incoming payload wholesale.
//  3. If the incoming payload has no usable sha but the existing row does,
//     keep the existing row — a shallow re-index must not overwrite a good
//     sha with an empty one (prevents concurrent-sync-vs-repair races).
//  4. Otherwise, shallow-merge JSONB with the incoming payload winning on
//     overlapping keys. This preserves enrichment-only fields (body, author,
//     changelog, submodules, enrichedAt, ...) when a shallower write arrives.
func (q *Queries) CreateArtifactVersion(ctx context.Context, arg CreateArtifactVersionParams) (ArtifactVersion, error) {
	row := q.db.QueryRow(ctx, createArtifactVersion,
		arg.ArtifactID,
		arg.Version,
		arg.SortOrder,
		arg.CommitBody,
	)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Version,
		&i.SortOrder,
		&i.Recommended,
		&i.CommitBody,
	)
	return i, err
}

const createArtifactVersionAsset = `-- name: CreateArtifactVersionAsset :one
INSERT INTO artifact_versioned_assets (artifact_version_id, classifier, sha256, download_url, md5, sha1, sha512, extension)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, artifact_version_id, classifier, sha256, download_url, md5, sha1, sha512, extension
`

type CreateArtifactVersionAssetParams struct {
	ArtifactVersionID int64
	Classifier        *string
	Sha256            *string
	DownloadUrl       string
	Md5               *string
	Sha1              *string
	Sha512            *string
	Extension         *string
}

func (q *Queries) CreateArtifactVersionAsset(ctx context.Context, arg CreateArtifactVersionAssetParams) (ArtifactVersionedAsset, error) {
	row := q.db.QueryRow(ctx, createArtifactVersionAsset,
		arg.ArtifactVersionID,
		arg.Classifier,
		arg.Sha256,
		arg.DownloadUrl,
		arg.Md5,
		arg.Sha1,
		arg.Sha512,
		arg.Extension,
	)
	var i ArtifactVersionedAsset
	err := row.Scan(
		&i.ID,
		&i.ArtifactVersionID,
		&i.Classifier,
		&i.Sha256,
		&i.DownloadUrl,
		&i.Md5,
		&i.Sha1,
		&i.Sha512,
		&i.Extension,
	)
	return i, err
}

const createArtifactVersionTag = `-- name: CreateArtifactVersionTag :one
INSERT INTO artifact_versioned_tags (artifact_version_id, tag_key, tag_value)
VALUES ($1, $2, $3)
ON CONFLICT (artifact_version_id, tag_key) DO UPDATE SET
    tag_value = EXCLUDED.tag_value
RETURNING artifact_version_id, tag_key, tag_value
`

type CreateArtifactVersionTagParams struct {
	ArtifactVersionID int64
	TagKey            string
	TagValue          string
}

func (q *Queries) CreateArtifactVersionTag(ctx context.Context, arg CreateArtifactVersionTagParams) (ArtifactVersionedTag, error) {
	row := q.db.QueryRow(ctx, createArtifactVersionTag, arg.ArtifactVersionID, arg.TagKey, arg.TagValue)
	var i ArtifactVersionedTag
	err := row.Scan(&i.ArtifactVersionID, &i.TagKey, &i.TagValue)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (maven_id, name, website)
VALUES ($1, $2, $3)
ON CONFLICT (maven_id) DO UPDATE SET
    name = EXCLUDED.name,
    website = EXCLUDED.website
RETURNING maven_id, name, website
`

type CreateGroupParams struct {
	MavenID string
	Name    string
	Website *string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.MavenID, arg.Name, arg.Website)
	var i Group
	err := row.Scan(&i.MavenID, &i.Name, &i.Website)
	return i, err
}

const deleteArtifactVersionAssets = `-- name: DeleteArtifactVersionAssets :exec
DELETE FROM artifact_versioned_assets
WHERE artifact_version_id = $1
`

func (q *Queries) DeleteArtifactVersionAssets(ctx context.Context, artifactVersionID int64) error {
	_, err := q.db.Exec(ctx, deleteArtifactVersionAssets, artifactVersionID)
	return err
}

const deleteArtifactVersionTags = `-- name: DeleteArtifactVersionTags :exec
DELETE FROM artifact_versioned_tags
WHERE artifact_version_id = $1
`

func (q *Queries) DeleteArtifactVersionTags(ctx context.Context, artifactVersionID int64) error {
	_, err := q.db.Exec(ctx, deleteArtifactVersionTags, artifactVersionID)
	return err
}

const getArtifactByGroupAndId = `-- name: GetArtifactByGroupAndId :one
SELECT id, group_id, artifact_id, name, website, issues, git_repositories, version_schema FROM artifacts
WHERE group_id = $1 AND artifact_id = $2
`

type GetArtifactByGroupAndIdParams struct {
	GroupID    string
	ArtifactID string
}

func (q *Queries) GetArtifactByGroupAndId(ctx context.Context, arg GetArtifactByGroupAndIdParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByGroupAndId, arg.GroupID, arg.ArtifactID)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ArtifactID,
		&i.Name,
		&i.Website,
		&i.Issues,
		&i.GitRepositories,
		&i.VersionSchema,
	)
	return i, err
}

const getArtifactVersion = `-- name: GetArtifactVersion :one
SELECT av.id, av.artifact_id, av.version, av.sort_order, av.recommended, av.commit_body
FROM artifact_versions av
JOIN artifacts a ON av.artifact_id = a.id
WHERE a.group_id = $1 AND a.artifact_id = $2 AND av.version = $3
`

type GetArtifactVersionParams struct {
	GroupID    string
	ArtifactID string
	Version    string
}

func (q *Queries) GetArtifactVersion(ctx context.Context, arg GetArtifactVersionParams) (ArtifactVersion, error) {
	row := q.db.QueryRow(ctx, getArtifactVersion, arg.GroupID, arg.ArtifactID, arg.Version)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Version,
		&i.SortOrder,
		&i.Recommended,
		&i.CommitBody,
	)
	return i, err
}

const getArtifactVersionByID = `-- name: GetArtifactVersionByID :one
SELECT id, artifact_id, version, sort_order, recommended, commit_body FROM artifact_versions WHERE id = $1
`

func (q *Queries) GetArtifactVersionByID(ctx context.Context, id int64) (ArtifactVersion, error) {
	row := q.db.QueryRow(ctx, getArtifactVersionByID, id)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Version,
		&i.SortOrder,
		&i.Recommended,
		&i.CommitBody,
	)
	return i, err
}

const getArtifactVersionSchema = `-- name: GetArtifactVersionSchema :one
SELECT version_schema FROM artifacts
WHERE group_id = $1 AND artifact_id = $2
`

type GetArtifactVersionSchemaParams struct {
	GroupID    string
	ArtifactID string
}

func (q *Queries) GetArtifactVersionSchema(ctx context.Context, arg GetArtifactVersionSchemaParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getArtifactVersionSchema, arg.GroupID, arg.ArtifactID)
	var version_schema []byte
	err := row.Scan(&version_schema)
	return version_schema, err
}

const getGroup = `-- name: GetGroup :one
SELECT maven_id, name, website FROM groups
WHERE maven_id = $1
`

func (q *Queries) GetGroup(ctx context.Context, mavenID string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, mavenID)
	var i Group
	err := row.Scan(&i.MavenID, &i.Name, &i.Website)
	return i, err
}

const getPreviousVersion = `-- name: GetPreviousVersion :one
SELECT av.id, av.artifact_id, av.version, av.sort_order, av.recommended, av.commit_body
FROM artifact_versions av
WHERE av.artifact_id = $1
  AND av.sort_order < $2 AND av.sort_order > 0
  AND av.commit_body IS NOT NULL
  AND av.commit_body->>'sha' IS NOT NULL
ORDER BY av.sort_order DESC
LIMIT 1
`

type GetPreviousVersionParams struct {
	ArtifactID int64
	SortOrder  int32
}

func (q *Queries) GetPreviousVersion(ctx context.Context, arg GetPreviousVersionParams) (ArtifactVersion, error) {
	row := q.db.QueryRow(ctx, getPreviousVersion, arg.ArtifactID, arg.SortOrder)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Version,
		&i.SortOrder,
		&i.Recommended,
		&i.CommitBody,
	)
	return i, err
}

const groupExistsByMavenID = `-- name: GroupExistsByMavenID :one
SELECT EXISTS(SELECT 1 FROM groups WHERE LOWER(maven_id) = LOWER($1)) AS exists
`

func (q *Queries) GroupExistsByMavenID(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, groupExistsByMavenID, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertNewArtifactVersion = `-- name: InsertNewArtifactVersion :exec
INSERT INTO artifact_versions (artifact_id, version)
VALUES ($1, $2)
ON CONFLICT (artifact_id, version) DO NOTHING
`

type InsertNewArtifactVersionParams struct {
	ArtifactID int64
	Version    string
}

// Inserts a bare artifact_versions row (no sort_order, no commit_body) and
// does nothing on conflict. Used by the version-sync path to announce "this
// version exists" without touching enrichment columns — overlapping sync
// runs must not clobber each other's sort_order or commit_body. The full
// upsert (CreateArtifactVersion) is reserved for ordering + enrichment
// writes that intentionally refresh sort_order / merge commit_body.
func (q *Queries) InsertNewArtifactVersion(ctx context.Context, arg InsertNewArtifactVersionParams) error {
	_, err := q.db.Exec(ctx, insertNewArtifactVersion, arg.ArtifactID, arg.Version)
	return err
}

const isVersionEnriched = `-- name: IsVersionEnriched :one
SELECT COALESCE((av.commit_body->>'enrichedAt') IS NOT NULL, false)::boolean AS enriched
FROM artifact_versions av
WHERE av.id = $1
`

func (q *Queries) IsVersionEnriched(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, isVersionEnriched, id)
	var enriched bool
	err := row.Scan(&enriched)
	return enriched, err
}

const listArtifactVersionAssets = `-- name: ListArtifactVersionAssets :many
SELECT id, artifact_version_id, classifier, sha256, download_url, md5, sha1, sha512, extension FROM artifact_versioned_assets
WHERE artifact_version_id = $1
`

func (q *Queries) ListArtifactVersionAssets(ctx context.Context, artifactVersionID int64) ([]ArtifactVersionedAsset, error) {
	rows, err := q.db.Query(ctx, listArtifactVersionAssets, artifactVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactVersionedAsset
	for rows.Next() {
		var i ArtifactVersionedAsset
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactVersionID,
			&i.Classifier,
			&i.Sha256,
			&i.DownloadUrl,
			&i.Md5,
			&i.Sha1,
			&i.Sha512,
			&i.Extension,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactVersionStringsByArtifactID = `-- name: ListArtifactVersionStringsByArtifactID :many
SELECT av.version
FROM artifact_versions av
WHERE av.artifact_id = $1
ORDER BY av.version
LIMIT $2 OFFSET $3
`

type ListArtifactVersionStringsByArtifactIDParams struct {
	ArtifactID int64
	Limit      int32
	Offset     int32
}

func (q *Queries) ListArtifactVersionStringsByArtifactID(ctx context.Context, arg ListArtifactVersionStringsByArtifactIDParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listArtifactVersionStringsByArtifactID, arg.ArtifactID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var version string
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactVersionTags = `-- name: ListArtifactVersionTags :many
SELECT artifact_version_id, tag_key, tag_value FROM artifact_versioned_tags
WHERE artifact_version_id = $1
`

func (q *Queries) ListArtifactVersionTags(ctx context.Context, artifactVersionID int64) ([]ArtifactVersionedTag, error) {
	rows, err := q.db.Query(ctx, listArtifactVersionTags, artifactVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactVersionedTag
	for rows.Next() {
		var i ArtifactVersionedTag
		if err := rows.Scan(&i.ArtifactVersionID, &i.TagKey, &i.TagValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactVersions = `-- name: ListArtifactVersions :many
SELECT av.id, av.artifact_id, av.version, av.sort_order, av.recommended, av.commit_body
FROM artifact_versions av
JOIN artifacts a ON av.artifact_id = a.id
WHERE a.group_id = $1 AND a.artifact_id = $2
ORDER BY av.sort_order DESC
`

type ListArtifactVersionsParams struct {
	GroupID    string
	ArtifactID string
}

func (q *Queries) ListArtifactVersions(ctx context.Context, arg ListArtifactVersionsParams) ([]ArtifactVersion, error) {
	rows, err := q.db.Query(ctx, listArtifactVersions, arg.GroupID, arg.ArtifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactVersion
	for rows.Next() {
		var i ArtifactVersion
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Version,
			&i.SortOrder,
			&i.Recommended,
			&i.CommitBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactVersionsPaginated = `-- name: ListArtifactVersionsPaginated :many
SELECT av.id, av.artifact_id, av.version, av.sort_order, av.recommended, av.commit_body
FROM artifact_versions av
JOIN artifacts a ON av.artifact_id = a.id
WHERE a.group_id = $1 AND a.artifact_id = $2
  AND ($5::boolean IS NULL OR av.recommended = $5)
ORDER BY av.sort_order DESC
LIMIT $3 OFFSET $4
`

type ListArtifactVersionsPaginatedParams struct {
	GroupID     string
	ArtifactID  string
	Limit       int32
	Offset      int32
	Recommended *bool
}

func (q *Queries) ListArtifactVersionsPaginated(ctx context.Context, arg ListArtifactVersionsPaginatedParams) ([]ArtifactVersion, error) {
	rows, err := q.db.Query(ctx, listArtifactVersionsPaginated,
		arg.GroupID,
		arg.ArtifactID,
		arg.Limit,
		arg.Offset,
		arg.Recommended,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactVersion
	for rows.Next() {
		var i ArtifactVersion
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Version,
			&i.SortOrder,
			&i.Recommended,
			&i.CommitBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByGroup = `-- name: ListArtifactsByGroup :many
SELECT id, group_id, artifact_id, name, website, issues, git_repositories, version_schema FROM artifacts
WHERE group_id = $1
`

func (q *Queries) ListArtifactsByGroup(ctx context.Context, groupID string) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.ArtifactID,
			&i.Name,
			&i.Website,
			&i.Issues,
			&i.GitRepositories,
			&i.VersionSchema,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctTagsByArtifact = `-- name: ListDistinctTagsByArtifact :many
SELECT t.tag_key, t.tag_value
FROM artifact_versioned_tags t
JOIN artifact_versions av ON t.artifact_version_id = av.id
JOIN artifacts a ON av.artifact_id = a.id
WHERE a.group_id = $1 AND a.artifact_id = $2
GROUP BY t.tag_key, t.tag_value
ORDER BY t.tag_key, MAX(av.sort_order) DESC
`

type ListDistinctTagsByArtifactParams struct {
	GroupID    string
	ArtifactID string
}

type ListDistinctTagsByArtifactRow struct {
	TagKey   string
	TagValue string
}

func (q *Queries) ListDistinctTagsByArtifact(ctx context.Context, arg ListDistinctTagsByArtifactParams) ([]ListDistinctTagsByArtifactRow, error) {
	rows, err := q.db.Query(ctx, listDistinctTagsByArtifact, arg.GroupID, arg.ArtifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDistinctTagsByArtifactRow
	for rows.Next() {
		var i ListDistinctTagsByArtifactRow
		if err := rows.Scan(&i.TagKey, &i.TagValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrichedVersions = `-- name: ListEnrichedVersions :many
SELECT av.id, av.artifact_id, av.version, av.sort_order, av.recommended, av.commit_body
FROM artifact_versions av
JOIN artifacts a ON av.artifact_id = a.id
WHERE a.group_id = $1 AND a.artifact_id = $2
  AND av.commit_body IS NOT NULL
  AND av.commit_body->>'sha' IS NOT NULL
  AND av.commit_body->>'enrichedAt' IS NOT NULL
  AND av.sort_order > 0
ORDER BY av.sort_order ASC
`

type ListEnrichedVersionsParams struct {
	GroupID    string
	ArtifactID string
}

func (q *Queries) ListEnrichedVersions(ctx context.Context, arg ListEnrichedVersionsParams) ([]ArtifactVersion, error) {
	rows, err := q.db.Query(ctx, listEnrichedVersions, arg.GroupID, arg.ArtifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactVersion
	for rows.Next() {
		var i ArtifactVersion
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Version,
			&i.SortOrder,
			&i.Recommended,
			&i.CommitBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT maven_id, name, website FROM groups
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.MavenID, &i.Name, &i.Website); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForVersions = `-- name: ListTagsForVersions :many
SELECT t.artifact_version_id, t.tag_key, t.tag_value
FROM artifact_versioned_tags t
WHERE t.artifact_version_id = ANY($1::bigint[])
ORDER BY t.artifact_version_id, t.tag_key
`

func (q *Queries) ListTagsForVersions(ctx context.Context, dollar_1 []int64) ([]ArtifactVersionedTag, error) {
	rows, err := q.db.Query(ctx, listTagsForVersions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactVersionedTag
	for rows.Next() {
		var i ArtifactVersionedTag
		if err := rows.Scan(&i.ArtifactVersionID, &i.TagKey, &i.TagValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionsNeedingChangelog = `-- name: ListVersionsNeedingChangelog :many
SELECT av.id, av.artifact_id, av.version, av.sort_order, av.recommended, av.commit_body
FROM artifact_versions av
JOIN artifacts a ON av.artifact_id = a.id
WHERE a.group_id = $1 AND a.artifact_id = $2
  AND av.commit_body IS NOT NULL
  AND av.commit_body->>'enrichedAt' IS NOT NULL
  AND av.commit_body->>'changelogStatus' = 'pending_predecessor'
ORDER BY av.sort_order ASC
`

type ListVersionsNeedingChangelogParams struct {
	GroupID    string
	ArtifactID string
}

func (q *Queries) ListVersionsNeedingChangelog(ctx context.Context, arg ListVersionsNeedingChangelogParams) ([]ArtifactVersion, error) {
	rows, err := q.db.Query(ctx, listVersionsNeedingChangelog, arg.GroupID, arg.ArtifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactVersion
	for rows.Next() {
		var i ArtifactVersion
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Version,
			&i.SortOrder,
			&i.Recommended,
			&i.CommitBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionsNeedingEnrichment = `-- name: ListVersionsNeedingEnrichment :many
SELECT av.id, av.artifact_id, av.version, av.sort_order, av.recommended, av.commit_body
FROM artifact_versions av
JOIN artifacts a ON av.artifact_id = a.id
WHERE a.group_id = $1 AND a.artifact_id = $2
  AND av.commit_body IS NOT NULL
  AND av.commit_body->>'sha' IS NOT NULL
  AND (av.commit_body->>'enrichedAt') IS NULL
  AND av.sort_order > 0
ORDER BY av.sort_order ASC
`

type ListVersionsNeedingEnrichmentParams struct {
	GroupID    string
	ArtifactID string
}

func (q *Queries) ListVersionsNeedingEnrichment(ctx context.Context, arg ListVersionsNeedingEnrichmentParams) ([]ArtifactVersion, error) {
	rows, err := q.db.Query(ctx, listVersionsNeedingEnrichment, arg.GroupID, arg.ArtifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactVersion
	for rows.Next() {
		var i ArtifactVersion
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Version,
			&i.SortOrder,
			&i.Recommended,
			&i.CommitBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtifactFields = `-- name: UpdateArtifactFields :one
UPDATE artifacts SET
  name = COALESCE($3, name),
  website = COALESCE($4, website),
  issues = COALESCE($5, issues),
  git_repositories = COALESCE($6::jsonb, git_repositories)
WHERE group_id = $1 AND artifact_id = $2
RETURNING id, group_id, artifact_id, name, website, issues, git_repositories, version_schema
`

type UpdateArtifactFieldsParams struct {
	GroupID         string
	ArtifactID      string
	Name            *string
	Website         *string
	Issues          *string
	GitRepositories []byte
}

func (q *Queries) UpdateArtifactFields(ctx context.Context, arg UpdateArtifactFieldsParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, updateArtifactFields,
		arg.GroupID,
		arg.ArtifactID,
		arg.Name,
		arg.Website,
		arg.Issues,
		arg.GitRepositories,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ArtifactID,
		&i.Name,
		&i.Website,
		&i.Issues,
		&i.GitRepositories,
		&i.VersionSchema,
	)
	return i, err
}

const updateArtifactVersionCommitBody = `-- name: UpdateArtifactVersionCommitBody :exec
UPDATE artifact_versions
SET commit_body = $2
WHERE id = $1
`

type UpdateArtifactVersionCommitBodyParams struct {
	ID         int64
	CommitBody []byte
}

func (q *Queries) UpdateArtifactVersionCommitBody(ctx context.Context, arg UpdateArtifactVersionCommitBodyParams) error {
	_, err := q.db.Exec(ctx, updateArtifactVersionCommitBody, arg.ID, arg.CommitBody)
	return err
}

const updateArtifactVersionOrder = `-- name: UpdateArtifactVersionOrder :exec
UPDATE artifact_versions
SET sort_order = $2, recommended = $3
WHERE id = $1
`

type UpdateArtifactVersionOrderParams struct {
	ID          int64
	SortOrder   int32
	Recommended bool
}

func (q *Queries) UpdateArtifactVersionOrder(ctx context.Context, arg UpdateArtifactVersionOrderParams) error {
	_, err := q.db.Exec(ctx, updateArtifactVersionOrder, arg.ID, arg.SortOrder, arg.Recommended)
	return err
}

const updateArtifactVersionSchema = `-- name: UpdateArtifactVersionSchema :exec
UPDATE artifacts SET version_schema = $3
WHERE group_id = $1 AND artifact_id = $2
`

type UpdateArtifactVersionSchemaParams struct {
	GroupID       string
	ArtifactID    string
	VersionSchema []byte
}

func (q *Queries) UpdateArtifactVersionSchema(ctx context.Context, arg UpdateArtifactVersionSchemaParams) error {
	_, err := q.db.Exec(ctx, updateArtifactVersionSchema, arg.GroupID, arg.ArtifactID, arg.VersionSchema)
	return err
}
