// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error)
	CreateArtifactVersion(ctx context.Context, arg CreateArtifactVersionParams) (ArtifactVersion, error)
	CreateArtifactVersionAsset(ctx context.Context, arg CreateArtifactVersionAssetParams) (ArtifactVersionedAsset, error)
	CreateArtifactVersionTag(ctx context.Context, arg CreateArtifactVersionTagParams) (ArtifactVersionedTag, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	DeleteArtifactVersionTags(ctx context.Context, artifactVersionID int64) error
	GetArtifactByGroupAndId(ctx context.Context, arg GetArtifactByGroupAndIdParams) (Artifact, error)
	GetArtifactVersion(ctx context.Context, arg GetArtifactVersionParams) (ArtifactVersion, error)
	GetArtifactVersionSchema(ctx context.Context, arg GetArtifactVersionSchemaParams) ([]byte, error)
	GetGroup(ctx context.Context, mavenID string) (Group, error)
	GroupExistsByMavenID(ctx context.Context, lower string) (bool, error)
	ListArtifactVersionAssets(ctx context.Context, artifactVersionID int64) ([]ArtifactVersionedAsset, error)
	ListArtifactVersionStringsByArtifactID(ctx context.Context, arg ListArtifactVersionStringsByArtifactIDParams) ([]string, error)
	ListArtifactVersionTags(ctx context.Context, artifactVersionID int64) ([]ArtifactVersionedTag, error)
	ListArtifactVersions(ctx context.Context, arg ListArtifactVersionsParams) ([]ArtifactVersion, error)
	ListArtifactVersionsPaginated(ctx context.Context, arg ListArtifactVersionsPaginatedParams) ([]ArtifactVersion, error)
	ListArtifactsByGroup(ctx context.Context, groupID string) ([]Artifact, error)
	ListDistinctTagsByArtifact(ctx context.Context, arg ListDistinctTagsByArtifactParams) ([]ListDistinctTagsByArtifactRow, error)
	ListGroups(ctx context.Context) ([]Group, error)
	ListTagsForVersions(ctx context.Context, dollar_1 []int64) ([]ArtifactVersionedTag, error)
	UpdateArtifactVersionCommitBody(ctx context.Context, arg UpdateArtifactVersionCommitBodyParams) error
	UpdateArtifactVersionOrder(ctx context.Context, arg UpdateArtifactVersionOrderParams) error
}

var _ Querier = (*Queries)(nil)
