// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (group_id, artifact_id, name, website, git_repositories, version_schema)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (group_id, artifact_id) DO UPDATE SET
    name = EXCLUDED.name,
    website = EXCLUDED.website,
    git_repositories = EXCLUDED.git_repositories,
    version_schema = EXCLUDED.version_schema
RETURNING id, group_id, artifact_id, name, website, git_repositories, version_schema
`

type CreateArtifactParams struct {
	GroupID         string
	ArtifactID      string
	Name            string
	Website         *string
	GitRepositories []byte
	VersionSchema   []byte
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.GroupID,
		arg.ArtifactID,
		arg.Name,
		arg.Website,
		arg.GitRepositories,
		arg.VersionSchema,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ArtifactID,
		&i.Name,
		&i.Website,
		&i.GitRepositories,
		&i.VersionSchema,
	)
	return i, err
}

const createArtifactVersion = `-- name: CreateArtifactVersion :one
INSERT INTO artifact_versions (artifact_id, version, sort_order, commit_body)
VALUES ($1, $2, $3, $4)
ON CONFLICT (artifact_id, version) DO UPDATE SET
    sort_order = EXCLUDED.sort_order,
    commit_body = EXCLUDED.commit_body
RETURNING id, artifact_id, version, sort_order, commit_body
`

type CreateArtifactVersionParams struct {
	ArtifactID int64
	Version    string
	SortOrder  int32
	CommitBody []byte
}

func (q *Queries) CreateArtifactVersion(ctx context.Context, arg CreateArtifactVersionParams) (ArtifactVersion, error) {
	row := q.db.QueryRow(ctx, createArtifactVersion,
		arg.ArtifactID,
		arg.Version,
		arg.SortOrder,
		arg.CommitBody,
	)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Version,
		&i.SortOrder,
		&i.CommitBody,
	)
	return i, err
}

const createArtifactVersionAsset = `-- name: CreateArtifactVersionAsset :one
INSERT INTO artifact_versioned_assets (artifact_version_id, classifier, sha256, download_url)
VALUES ($1, $2, $3, $4)
RETURNING id, artifact_version_id, classifier, sha256, download_url
`

type CreateArtifactVersionAssetParams struct {
	ArtifactVersionID int64
	Classifier        *string
	Sha256            *string
	DownloadUrl       string
}

func (q *Queries) CreateArtifactVersionAsset(ctx context.Context, arg CreateArtifactVersionAssetParams) (ArtifactVersionedAsset, error) {
	row := q.db.QueryRow(ctx, createArtifactVersionAsset,
		arg.ArtifactVersionID,
		arg.Classifier,
		arg.Sha256,
		arg.DownloadUrl,
	)
	var i ArtifactVersionedAsset
	err := row.Scan(
		&i.ID,
		&i.ArtifactVersionID,
		&i.Classifier,
		&i.Sha256,
		&i.DownloadUrl,
	)
	return i, err
}

const createArtifactVersionTag = `-- name: CreateArtifactVersionTag :one
INSERT INTO artifact_versioned_tags (artifact_version_id, tag_key, tag_value)
VALUES ($1, $2, $3)
ON CONFLICT (artifact_version_id, tag_key) DO UPDATE SET
    tag_value = EXCLUDED.tag_value
RETURNING artifact_version_id, tag_key, tag_value
`

type CreateArtifactVersionTagParams struct {
	ArtifactVersionID int64
	TagKey            string
	TagValue          string
}

func (q *Queries) CreateArtifactVersionTag(ctx context.Context, arg CreateArtifactVersionTagParams) (ArtifactVersionedTag, error) {
	row := q.db.QueryRow(ctx, createArtifactVersionTag, arg.ArtifactVersionID, arg.TagKey, arg.TagValue)
	var i ArtifactVersionedTag
	err := row.Scan(&i.ArtifactVersionID, &i.TagKey, &i.TagValue)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (maven_id, name, website)
VALUES ($1, $2, $3)
ON CONFLICT (maven_id) DO UPDATE SET
    name = EXCLUDED.name,
    website = EXCLUDED.website
RETURNING maven_id, name, website
`

type CreateGroupParams struct {
	MavenID string
	Name    string
	Website *string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.MavenID, arg.Name, arg.Website)
	var i Group
	err := row.Scan(&i.MavenID, &i.Name, &i.Website)
	return i, err
}

const deleteArtifactVersionTags = `-- name: DeleteArtifactVersionTags :exec
DELETE FROM artifact_versioned_tags
WHERE artifact_version_id = $1
`

func (q *Queries) DeleteArtifactVersionTags(ctx context.Context, artifactVersionID int64) error {
	_, err := q.db.Exec(ctx, deleteArtifactVersionTags, artifactVersionID)
	return err
}

const getArtifactByGroupAndId = `-- name: GetArtifactByGroupAndId :one
SELECT id, group_id, artifact_id, name, website, git_repositories, version_schema FROM artifacts
WHERE group_id = $1 AND artifact_id = $2
`

type GetArtifactByGroupAndIdParams struct {
	GroupID    string
	ArtifactID string
}

func (q *Queries) GetArtifactByGroupAndId(ctx context.Context, arg GetArtifactByGroupAndIdParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByGroupAndId, arg.GroupID, arg.ArtifactID)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ArtifactID,
		&i.Name,
		&i.Website,
		&i.GitRepositories,
		&i.VersionSchema,
	)
	return i, err
}

const getArtifactVersion = `-- name: GetArtifactVersion :one
SELECT av.id, av.artifact_id, av.version, av.sort_order, av.commit_body
FROM artifact_versions av
JOIN artifacts a ON av.artifact_id = a.id
WHERE a.group_id = $1 AND a.artifact_id = $2 AND av.version = $3
`

type GetArtifactVersionParams struct {
	GroupID    string
	ArtifactID string
	Version    string
}

func (q *Queries) GetArtifactVersion(ctx context.Context, arg GetArtifactVersionParams) (ArtifactVersion, error) {
	row := q.db.QueryRow(ctx, getArtifactVersion, arg.GroupID, arg.ArtifactID, arg.Version)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Version,
		&i.SortOrder,
		&i.CommitBody,
	)
	return i, err
}

const getArtifactVersionSchema = `-- name: GetArtifactVersionSchema :one
SELECT version_schema FROM artifacts
WHERE group_id = $1 AND artifact_id = $2
`

type GetArtifactVersionSchemaParams struct {
	GroupID    string
	ArtifactID string
}

func (q *Queries) GetArtifactVersionSchema(ctx context.Context, arg GetArtifactVersionSchemaParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getArtifactVersionSchema, arg.GroupID, arg.ArtifactID)
	var version_schema []byte
	err := row.Scan(&version_schema)
	return version_schema, err
}

const getGroup = `-- name: GetGroup :one
SELECT maven_id, name, website FROM groups
WHERE maven_id = $1
`

func (q *Queries) GetGroup(ctx context.Context, mavenID string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, mavenID)
	var i Group
	err := row.Scan(&i.MavenID, &i.Name, &i.Website)
	return i, err
}

const groupExistsByMavenID = `-- name: GroupExistsByMavenID :one
SELECT EXISTS(SELECT 1 FROM groups WHERE LOWER(maven_id) = LOWER($1)) AS exists
`

func (q *Queries) GroupExistsByMavenID(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, groupExistsByMavenID, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listArtifactVersionAssets = `-- name: ListArtifactVersionAssets :many
SELECT id, artifact_version_id, classifier, sha256, download_url FROM artifact_versioned_assets
WHERE artifact_version_id = $1
`

func (q *Queries) ListArtifactVersionAssets(ctx context.Context, artifactVersionID int64) ([]ArtifactVersionedAsset, error) {
	rows, err := q.db.Query(ctx, listArtifactVersionAssets, artifactVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactVersionedAsset
	for rows.Next() {
		var i ArtifactVersionedAsset
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactVersionID,
			&i.Classifier,
			&i.Sha256,
			&i.DownloadUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactVersionStringsByArtifactID = `-- name: ListArtifactVersionStringsByArtifactID :many
SELECT av.version
FROM artifact_versions av
WHERE av.artifact_id = $1
ORDER BY av.version
LIMIT $2 OFFSET $3
`

type ListArtifactVersionStringsByArtifactIDParams struct {
	ArtifactID int64
	Limit      int32
	Offset     int32
}

func (q *Queries) ListArtifactVersionStringsByArtifactID(ctx context.Context, arg ListArtifactVersionStringsByArtifactIDParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listArtifactVersionStringsByArtifactID, arg.ArtifactID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var version string
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactVersionTags = `-- name: ListArtifactVersionTags :many
SELECT artifact_version_id, tag_key, tag_value FROM artifact_versioned_tags
WHERE artifact_version_id = $1
`

func (q *Queries) ListArtifactVersionTags(ctx context.Context, artifactVersionID int64) ([]ArtifactVersionedTag, error) {
	rows, err := q.db.Query(ctx, listArtifactVersionTags, artifactVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactVersionedTag
	for rows.Next() {
		var i ArtifactVersionedTag
		if err := rows.Scan(&i.ArtifactVersionID, &i.TagKey, &i.TagValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactVersions = `-- name: ListArtifactVersions :many
SELECT av.id, av.artifact_id, av.version, av.sort_order, av.commit_body
FROM artifact_versions av
JOIN artifacts a ON av.artifact_id = a.id
WHERE a.group_id = $1 AND a.artifact_id = $2
ORDER BY av.sort_order DESC
`

type ListArtifactVersionsParams struct {
	GroupID    string
	ArtifactID string
}

func (q *Queries) ListArtifactVersions(ctx context.Context, arg ListArtifactVersionsParams) ([]ArtifactVersion, error) {
	rows, err := q.db.Query(ctx, listArtifactVersions, arg.GroupID, arg.ArtifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactVersion
	for rows.Next() {
		var i ArtifactVersion
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Version,
			&i.SortOrder,
			&i.CommitBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByGroup = `-- name: ListArtifactsByGroup :many
SELECT id, group_id, artifact_id, name, website, git_repositories, version_schema FROM artifacts
WHERE group_id = $1
`

func (q *Queries) ListArtifactsByGroup(ctx context.Context, groupID string) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.ArtifactID,
			&i.Name,
			&i.Website,
			&i.GitRepositories,
			&i.VersionSchema,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT maven_id, name, website FROM groups
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.MavenID, &i.Name, &i.Website); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtifactVersionCommitBody = `-- name: UpdateArtifactVersionCommitBody :exec
UPDATE artifact_versions
SET commit_body = $2
WHERE id = $1
`

type UpdateArtifactVersionCommitBodyParams struct {
	ID         int64
	CommitBody []byte
}

func (q *Queries) UpdateArtifactVersionCommitBody(ctx context.Context, arg UpdateArtifactVersionCommitBodyParams) error {
	_, err := q.db.Exec(ctx, updateArtifactVersionCommitBody, arg.ID, arg.CommitBody)
	return err
}

const updateArtifactVersionOrder = `-- name: UpdateArtifactVersionOrder :exec
UPDATE artifact_versions
SET sort_order = $2
WHERE id = $1
`

type UpdateArtifactVersionOrderParams struct {
	ID        int64
	SortOrder int32
}

func (q *Queries) UpdateArtifactVersionOrder(ctx context.Context, arg UpdateArtifactVersionOrderParams) error {
	_, err := q.db.Exec(ctx, updateArtifactVersionOrder, arg.ID, arg.SortOrder)
	return err
}
