//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for VersionSchemaVariantsSegmentsParseAs.
const (
	Dotted    VersionSchemaVariantsSegmentsParseAs = "dotted"
	Ignore    VersionSchemaVariantsSegmentsParseAs = "ignore"
	Integer   VersionSchemaVariantsSegmentsParseAs = "integer"
	Minecraft VersionSchemaVariantsSegmentsParseAs = "minecraft"
)

// Valid indicates whether the value is a known member of the VersionSchemaVariantsSegmentsParseAs enum.
func (e VersionSchemaVariantsSegmentsParseAs) Valid() bool {
	switch e {
	case Dotted:
		return true
	case Ignore:
		return true
	case Integer:
		return true
	case Minecraft:
		return true
	default:
		return false
	}
}

// Defines values for TriggerSyncParamsSource.
const (
	Metadata TriggerSyncParamsSource = "metadata"
	Search   TriggerSyncParamsSource = "search"
)

// Valid indicates whether the value is a known member of the TriggerSyncParamsSource enum.
func (e TriggerSyncParamsSource) Valid() bool {
	switch e {
	case Metadata:
		return true
	case Search:
		return true
	default:
		return false
	}
}

// Artifact defines model for Artifact.
type Artifact struct {
	Coordinates struct {
		ArtifactId string `json:"artifactId"`
		GroupId    string `json:"groupId"`
	} `json:"coordinates"`

	// DisplayName The name of the artifact in the desired format to be displayed on the web or referenced in communication
	DisplayName   *string             `json:"displayName,omitempty"`
	GitRepository *[]string           `json:"gitRepository,omitempty"`
	Issues        *string             `json:"issues,omitempty"`
	Tags          map[string][]string `json:"tags"`
	Type          string              `json:"type"`
	Website       *string             `json:"website,omitempty"`
}

// ArtifactRegistration defines model for ArtifactRegistration.
type ArtifactRegistration struct {
	// ArtifactId The maven style artifact id
	ArtifactId string `json:"artifactId"`

	// DisplayName The name of the artifact in the desired format to be displayed on the web or referenced in communication
	DisplayName string `json:"displayName"`

	// GitRepository An array of git repository URLs
	GitRepository []string `json:"gitRepository"`

	// Issues The issues/tracker URL (optional)
	Issues *string `json:"issues,omitempty"`

	// Website The website URL (optional)
	Website *string `json:"website,omitempty"`
}

// Asset defines model for Asset.
type Asset struct {
	// Classifier The classifier of the jar asset. Usually can be
	// understood as the "variant" of the asset. Some
	// variants are specific to an operating sytem, while
	// others are variants of the executable available. In
	// the case of Sponge's main assets, the empty string
	// classifier is the "download and run" asset desired.
	Classifier *string `json:"classifier,omitempty"`

	// DownloadUrl The direct download URL
	DownloadUrl *string `json:"downloadUrl,omitempty"`

	// Extension The file extension of the asset.
	Extension *string `json:"extension,omitempty"`
	Md5       *string `json:"md5,omitempty"`
	Sha1      *string `json:"sha1,omitempty"`
}

// Commit defines model for Commit.
type Commit struct {
	Author *struct {
		Email *string `json:"email,omitempty"`
		Name  *string `json:"name,omitempty"`
	} `json:"author,omitempty"`
	Body       *string             `json:"body,omitempty"`
	CommitDate *openapi_types.Date `json:"commitDate,omitempty"`
	Link       *string             `json:"link,omitempty"`
	Message    *string             `json:"message,omitempty"`
	Sha        *string             `json:"sha,omitempty"`
}

// Group defines model for Group.
type Group struct {
	// GroupCoordinates Maven style group coordinates
	GroupCoordinates string `json:"groupCoordinates"`

	// Name The name of the group
	Name string `json:"name"`

	// Website The website url
	Website *string `json:"website,omitempty"`
}

// GroupArtifacts defines model for GroupArtifacts.
type GroupArtifacts struct {
	// ArtifactIds The artifact id's indexed for the group
	ArtifactIds []string `json:"artifactIds"`
	Type        string   `json:"type"`
}

// Groups defines model for Groups.
type Groups struct {
	Groups []Group `json:"groups"`
}

// VersionInfo defines model for VersionInfo.
type VersionInfo struct {
	Assets *[]Asset `json:"assets,omitempty"`
	Commit *struct {
		Commits *[]struct {
			Commit           *Commit   `json:"commit,omitempty"`
			SubmoduleCommits *[]Commit `json:"submoduleCommits,omitempty"`
		} `json:"commits,omitempty"`
	} `json:"commit,omitempty"`
	Coordinates *struct {
		ArtifactId *string `json:"artifactId,omitempty"`
		GroupId    *string `json:"groupId,omitempty"`
		Version    *string `json:"version,omitempty"`
	} `json:"coordinates,omitempty"`

	// Recommended Whether the artifact is considered a "standard release" version or if it is still in development.
	Recommended *bool              `json:"recommended,omitempty"`
	Tags        *map[string]string `json:"tags,omitempty"`
}

// VersionSchema defines model for VersionSchema.
type VersionSchema struct {
	// UseMojangManifest Whether to fetch Mojang version manifest for Minecraft version ordering
	UseMojangManifest *bool `json:"use_mojang_manifest,omitempty"`
	Variants          []struct {
		// Name Human-readable variant name (e.g. "current", "beta-era")
		Name string `json:"name"`

		// Pattern Regex with named capture groups for version parsing
		Pattern  string `json:"pattern"`
		Segments []struct {
			// Name Named capture group to match
			Name string `json:"name"`

			// ParseAs How to parse and compare this segment
			ParseAs VersionSchemaVariantsSegmentsParseAs `json:"parse_as"`

			// TagKey If set, produces a version tag with this key
			TagKey *string `json:"tag_key,omitempty"`
		} `json:"segments"`
	} `json:"variants"`
}

// VersionSchemaVariantsSegmentsParseAs How to parse and compare this segment
type VersionSchemaVariantsSegmentsParseAs string

// ArtifactID defines model for ArtifactID.
type ArtifactID = string

// GroupID defines model for GroupID.
type GroupID = string

// UpdateArtifactJSONBody defines parameters for UpdateArtifact.
type UpdateArtifactJSONBody struct {
	// DisplayName Display name for the artifact
	DisplayName *string `json:"displayName,omitempty"`

	// GitRepository Git repository URLs
	GitRepository *[]string `json:"gitRepository,omitempty"`
	Issues        *string   `json:"issues,omitempty"`
	Website       *string   `json:"website,omitempty"`
}

// GetLatestVersionParams defines parameters for GetLatestVersion.
type GetLatestVersionParams struct {
	Recommended *bool   `form:"recommended,omitempty" json:"recommended,omitempty"`
	Tags        *string `form:"tags,omitempty" json:"tags,omitempty"`
}

// TriggerSyncParams defines parameters for TriggerSync.
type TriggerSyncParams struct {
	// Source Which version-discovery schedule to trigger. `metadata` fires the
	// fast 2-minute maven-metadata.xml schedule; `search` fires the
	// hourly REST-pagination correctness backstop schedule. Defaults
	// to `metadata` (the fast path) when omitted.
	Source *TriggerSyncParamsSource `form:"source,omitempty" json:"source,omitempty"`
}

// TriggerSyncParamsSource defines parameters for TriggerSync.
type TriggerSyncParamsSource string

// GetVersionsParams defines parameters for GetVersions.
type GetVersionsParams struct {
	Recommended *bool   `form:"recommended,omitempty" json:"recommended,omitempty"`
	Limit       *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset      *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Tags        *string `form:"tags,omitempty" json:"tags,omitempty"`
}

// RegisterGroupJSONRequestBody defines body for RegisterGroup for application/json ContentType.
type RegisterGroupJSONRequestBody = Group

// RegisterArtifactJSONRequestBody defines body for RegisterArtifact for application/json ContentType.
type RegisterArtifactJSONRequestBody = ArtifactRegistration

// UpdateArtifactJSONRequestBody defines body for UpdateArtifact for application/json ContentType.
type UpdateArtifactJSONRequestBody UpdateArtifactJSONBody

// PutArtifactSchemaJSONRequestBody defines body for PutArtifactSchema for application/json ContentType.
type PutArtifactSchemaJSONRequestBody = VersionSchema

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /groups)
	GetGroups(w http.ResponseWriter, r *http.Request)

	// (POST /groups)
	RegisterGroup(w http.ResponseWriter, r *http.Request)

	// (GET /groups/{groupID})
	GetGroup(w http.ResponseWriter, r *http.Request, groupID GroupID)

	// (GET /groups/{groupID}/artifacts)
	GetArtifacts(w http.ResponseWriter, r *http.Request, groupID GroupID)

	// (POST /groups/{groupID}/artifacts)
	RegisterArtifact(w http.ResponseWriter, r *http.Request, groupID GroupID)

	// (GET /groups/{groupID}/artifacts/{artifactID})
	GetArtifact(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID)

	// (PATCH /groups/{groupID}/artifacts/{artifactID})
	UpdateArtifact(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID)

	// (GET /groups/{groupID}/artifacts/{artifactID}/latest)
	GetLatestVersion(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID, params GetLatestVersionParams)

	// (GET /groups/{groupID}/artifacts/{artifactID}/schema)
	GetArtifactSchema(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID)

	// (PUT /groups/{groupID}/artifacts/{artifactID}/schema)
	PutArtifactSchema(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID)

	// (POST /groups/{groupID}/artifacts/{artifactID}/sync)
	TriggerSync(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID, params TriggerSyncParams)

	// (GET /groups/{groupID}/artifacts/{artifactID}/versions)
	GetVersions(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID, params GetVersionsParams)

	// (GET /groups/{groupID}/artifacts/{artifactID}/versions/{versionID})
	GetVersionInfo(w http.ResponseWriter, r *http.Request, groupID string, artifactID string, versionID string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetGroups operation middleware
func (siw *ServerInterfaceWrapper) GetGroups(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroups(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterGroup operation middleware
func (siw *ServerInterfaceWrapper) RegisterGroup(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterGroup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroup(w, r, groupID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArtifacts operation middleware
func (siw *ServerInterfaceWrapper) GetArtifacts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtifacts(w, r, groupID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterArtifact operation middleware
func (siw *ServerInterfaceWrapper) RegisterArtifact(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterArtifact(w, r, groupID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArtifact operation middleware
func (siw *ServerInterfaceWrapper) GetArtifact(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	// ------------- Path parameter "artifactID" -------------
	var artifactID ArtifactID

	err = runtime.BindStyledParameterWithOptions("simple", "artifactID", r.PathValue("artifactID"), &artifactID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artifactID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtifact(w, r, groupID, artifactID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateArtifact operation middleware
func (siw *ServerInterfaceWrapper) UpdateArtifact(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	// ------------- Path parameter "artifactID" -------------
	var artifactID ArtifactID

	err = runtime.BindStyledParameterWithOptions("simple", "artifactID", r.PathValue("artifactID"), &artifactID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artifactID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateArtifact(w, r, groupID, artifactID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLatestVersion operation middleware
func (siw *ServerInterfaceWrapper) GetLatestVersion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	// ------------- Path parameter "artifactID" -------------
	var artifactID ArtifactID

	err = runtime.BindStyledParameterWithOptions("simple", "artifactID", r.PathValue("artifactID"), &artifactID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artifactID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestVersionParams

	// ------------- Optional query parameter "recommended" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "recommended", r.URL.Query(), &params.Recommended, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recommended", Err: err})
		return
	}

	// ------------- Optional query parameter "tags" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tags", r.URL.Query(), &params.Tags, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tags", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLatestVersion(w, r, groupID, artifactID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArtifactSchema operation middleware
func (siw *ServerInterfaceWrapper) GetArtifactSchema(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	// ------------- Path parameter "artifactID" -------------
	var artifactID ArtifactID

	err = runtime.BindStyledParameterWithOptions("simple", "artifactID", r.PathValue("artifactID"), &artifactID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artifactID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtifactSchema(w, r, groupID, artifactID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutArtifactSchema operation middleware
func (siw *ServerInterfaceWrapper) PutArtifactSchema(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	// ------------- Path parameter "artifactID" -------------
	var artifactID ArtifactID

	err = runtime.BindStyledParameterWithOptions("simple", "artifactID", r.PathValue("artifactID"), &artifactID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artifactID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutArtifactSchema(w, r, groupID, artifactID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerSync(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	// ------------- Path parameter "artifactID" -------------
	var artifactID ArtifactID

	err = runtime.BindStyledParameterWithOptions("simple", "artifactID", r.PathValue("artifactID"), &artifactID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artifactID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params TriggerSyncParams

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", r.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSync(w, r, groupID, artifactID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersions operation middleware
func (siw *ServerInterfaceWrapper) GetVersions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	// ------------- Path parameter "artifactID" -------------
	var artifactID ArtifactID

	err = runtime.BindStyledParameterWithOptions("simple", "artifactID", r.PathValue("artifactID"), &artifactID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artifactID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVersionsParams

	// ------------- Optional query parameter "recommended" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "recommended", r.URL.Query(), &params.Recommended, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recommended", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "tags" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tags", r.URL.Query(), &params.Tags, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tags", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersions(w, r, groupID, artifactID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersionInfo operation middleware
func (siw *ServerInterfaceWrapper) GetVersionInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID string

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	// ------------- Path parameter "artifactID" -------------
	var artifactID string

	err = runtime.BindStyledParameterWithOptions("simple", "artifactID", r.PathValue("artifactID"), &artifactID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artifactID", Err: err})
		return
	}

	// ------------- Path parameter "versionID" -------------
	var versionID string

	err = runtime.BindStyledParameterWithOptions("simple", "versionID", r.PathValue("versionID"), &versionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "versionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersionInfo(w, r, groupID, artifactID, versionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/groups", wrapper.GetGroups)
	m.HandleFunc("POST "+options.BaseURL+"/groups", wrapper.RegisterGroup)
	m.HandleFunc("GET "+options.BaseURL+"/groups/{groupID}", wrapper.GetGroup)
	m.HandleFunc("GET "+options.BaseURL+"/groups/{groupID}/artifacts", wrapper.GetArtifacts)
	m.HandleFunc("POST "+options.BaseURL+"/groups/{groupID}/artifacts", wrapper.RegisterArtifact)
	m.HandleFunc("GET "+options.BaseURL+"/groups/{groupID}/artifacts/{artifactID}", wrapper.GetArtifact)
	m.HandleFunc("PATCH "+options.BaseURL+"/groups/{groupID}/artifacts/{artifactID}", wrapper.UpdateArtifact)
	m.HandleFunc("GET "+options.BaseURL+"/groups/{groupID}/artifacts/{artifactID}/latest", wrapper.GetLatestVersion)
	m.HandleFunc("GET "+options.BaseURL+"/groups/{groupID}/artifacts/{artifactID}/schema", wrapper.GetArtifactSchema)
	m.HandleFunc("PUT "+options.BaseURL+"/groups/{groupID}/artifacts/{artifactID}/schema", wrapper.PutArtifactSchema)
	m.HandleFunc("POST "+options.BaseURL+"/groups/{groupID}/artifacts/{artifactID}/sync", wrapper.TriggerSync)
	m.HandleFunc("GET "+options.BaseURL+"/groups/{groupID}/artifacts/{artifactID}/versions", wrapper.GetVersions)
	m.HandleFunc("GET "+options.BaseURL+"/groups/{groupID}/artifacts/{artifactID}/versions/{versionID}", wrapper.GetVersionInfo)

	return m
}

type GetGroupsRequestObject struct {
}

type GetGroupsResponseObject interface {
	VisitGetGroupsResponse(w http.ResponseWriter) error
}

type GetGroups200JSONResponse Groups

func (response GetGroups200JSONResponse) VisitGetGroupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RegisterGroupRequestObject struct {
	Body *RegisterGroupJSONRequestBody
}

type RegisterGroupResponseObject interface {
	VisitRegisterGroupResponse(w http.ResponseWriter) error
}

type RegisterGroup201JSONResponse Group

func (response RegisterGroup201JSONResponse) VisitRegisterGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type GetGroupRequestObject struct {
	GroupID GroupID `json:"groupID"`
}

type GetGroupResponseObject interface {
	VisitGetGroupResponse(w http.ResponseWriter) error
}

type GetGroup200JSONResponse Group

func (response GetGroup200JSONResponse) VisitGetGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGroup404Response struct {
}

func (response GetGroup404Response) VisitGetGroupResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetArtifactsRequestObject struct {
	GroupID GroupID `json:"groupID"`
}

type GetArtifactsResponseObject interface {
	VisitGetArtifactsResponse(w http.ResponseWriter) error
}

type GetArtifacts200JSONResponse GroupArtifacts

func (response GetArtifacts200JSONResponse) VisitGetArtifactsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RegisterArtifactRequestObject struct {
	GroupID GroupID `json:"groupID"`
	Body    *RegisterArtifactJSONRequestBody
}

type RegisterArtifactResponseObject interface {
	VisitRegisterArtifactResponse(w http.ResponseWriter) error
}

type RegisterArtifact201JSONResponse Artifact

func (response RegisterArtifact201JSONResponse) VisitRegisterArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterArtifact400Response struct {
}

func (response RegisterArtifact400Response) VisitRegisterArtifactResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type RegisterArtifact404Response struct {
}

func (response RegisterArtifact404Response) VisitRegisterArtifactResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type RegisterArtifact409Response struct {
}

func (response RegisterArtifact409Response) VisitRegisterArtifactResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type GetArtifactRequestObject struct {
	GroupID    GroupID    `json:"groupID"`
	ArtifactID ArtifactID `json:"artifactID"`
}

type GetArtifactResponseObject interface {
	VisitGetArtifactResponse(w http.ResponseWriter) error
}

type GetArtifact200JSONResponse Artifact

func (response GetArtifact200JSONResponse) VisitGetArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArtifact404Response struct {
}

func (response GetArtifact404Response) VisitGetArtifactResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateArtifactRequestObject struct {
	GroupID    GroupID    `json:"groupID"`
	ArtifactID ArtifactID `json:"artifactID"`
	Body       *UpdateArtifactJSONRequestBody
}

type UpdateArtifactResponseObject interface {
	VisitUpdateArtifactResponse(w http.ResponseWriter) error
}

type UpdateArtifact200JSONResponse Artifact

func (response UpdateArtifact200JSONResponse) VisitUpdateArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateArtifact404Response struct {
}

func (response UpdateArtifact404Response) VisitUpdateArtifactResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetLatestVersionRequestObject struct {
	GroupID    GroupID    `json:"groupID"`
	ArtifactID ArtifactID `json:"artifactID"`
	Params     GetLatestVersionParams
}

type GetLatestVersionResponseObject interface {
	VisitGetLatestVersionResponse(w http.ResponseWriter) error
}

type GetLatestVersion200JSONResponse VersionInfo

func (response GetLatestVersion200JSONResponse) VisitGetLatestVersionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLatestVersion404Response struct {
}

func (response GetLatestVersion404Response) VisitGetLatestVersionResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetArtifactSchemaRequestObject struct {
	GroupID    GroupID    `json:"groupID"`
	ArtifactID ArtifactID `json:"artifactID"`
}

type GetArtifactSchemaResponseObject interface {
	VisitGetArtifactSchemaResponse(w http.ResponseWriter) error
}

type GetArtifactSchema200JSONResponse VersionSchema

func (response GetArtifactSchema200JSONResponse) VisitGetArtifactSchemaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArtifactSchema404Response struct {
}

func (response GetArtifactSchema404Response) VisitGetArtifactSchemaResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PutArtifactSchemaRequestObject struct {
	GroupID    GroupID    `json:"groupID"`
	ArtifactID ArtifactID `json:"artifactID"`
	Body       *PutArtifactSchemaJSONRequestBody
}

type PutArtifactSchemaResponseObject interface {
	VisitPutArtifactSchemaResponse(w http.ResponseWriter) error
}

type PutArtifactSchema200JSONResponse VersionSchema

func (response PutArtifactSchema200JSONResponse) VisitPutArtifactSchemaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutArtifactSchema400Response struct {
}

func (response PutArtifactSchema400Response) VisitPutArtifactSchemaResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PutArtifactSchema404Response struct {
}

func (response PutArtifactSchema404Response) VisitPutArtifactSchemaResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type TriggerSyncRequestObject struct {
	GroupID    GroupID    `json:"groupID"`
	ArtifactID ArtifactID `json:"artifactID"`
	Params     TriggerSyncParams
}

type TriggerSyncResponseObject interface {
	VisitTriggerSyncResponse(w http.ResponseWriter) error
}

type TriggerSync200JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response TriggerSync200JSONResponse) VisitTriggerSyncResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TriggerSync400Response struct {
}

func (response TriggerSync400Response) VisitTriggerSyncResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type TriggerSync404Response struct {
}

func (response TriggerSync404Response) VisitTriggerSyncResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type TriggerSync500Response struct {
}

func (response TriggerSync500Response) VisitTriggerSyncResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetVersionsRequestObject struct {
	GroupID    GroupID    `json:"groupID"`
	ArtifactID ArtifactID `json:"artifactID"`
	Params     GetVersionsParams
}

type GetVersionsResponseObject interface {
	VisitGetVersionsResponse(w http.ResponseWriter) error
}

type GetVersions200JSONResponse struct {
	Artifacts *map[string]struct {
		Recommended *bool              `json:"recommended,omitempty"`
		TagValues   *map[string]string `json:"tagValues,omitempty"`
	} `json:"artifacts,omitempty"`

	// Limit The limit used for this page of results
	Limit *int `json:"limit,omitempty"`

	// Offset The offset used for this page of results
	Offset *int `json:"offset,omitempty"`

	// Size Total number of versions matching the query (for pagination)
	Size *int `json:"size,omitempty"`
}

func (response GetVersions200JSONResponse) VisitGetVersionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVersions404Response struct {
}

func (response GetVersions404Response) VisitGetVersionsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetVersionInfoRequestObject struct {
	GroupID    string `json:"groupID"`
	ArtifactID string `json:"artifactID"`
	VersionID  string `json:"versionID"`
}

type GetVersionInfoResponseObject interface {
	VisitGetVersionInfoResponse(w http.ResponseWriter) error
}

type GetVersionInfo200JSONResponse VersionInfo

func (response GetVersionInfo200JSONResponse) VisitGetVersionInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVersionInfo404Response struct {
}

func (response GetVersionInfo404Response) VisitGetVersionInfoResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /groups)
	GetGroups(ctx context.Context, request GetGroupsRequestObject) (GetGroupsResponseObject, error)

	// (POST /groups)
	RegisterGroup(ctx context.Context, request RegisterGroupRequestObject) (RegisterGroupResponseObject, error)

	// (GET /groups/{groupID})
	GetGroup(ctx context.Context, request GetGroupRequestObject) (GetGroupResponseObject, error)

	// (GET /groups/{groupID}/artifacts)
	GetArtifacts(ctx context.Context, request GetArtifactsRequestObject) (GetArtifactsResponseObject, error)

	// (POST /groups/{groupID}/artifacts)
	RegisterArtifact(ctx context.Context, request RegisterArtifactRequestObject) (RegisterArtifactResponseObject, error)

	// (GET /groups/{groupID}/artifacts/{artifactID})
	GetArtifact(ctx context.Context, request GetArtifactRequestObject) (GetArtifactResponseObject, error)

	// (PATCH /groups/{groupID}/artifacts/{artifactID})
	UpdateArtifact(ctx context.Context, request UpdateArtifactRequestObject) (UpdateArtifactResponseObject, error)

	// (GET /groups/{groupID}/artifacts/{artifactID}/latest)
	GetLatestVersion(ctx context.Context, request GetLatestVersionRequestObject) (GetLatestVersionResponseObject, error)

	// (GET /groups/{groupID}/artifacts/{artifactID}/schema)
	GetArtifactSchema(ctx context.Context, request GetArtifactSchemaRequestObject) (GetArtifactSchemaResponseObject, error)

	// (PUT /groups/{groupID}/artifacts/{artifactID}/schema)
	PutArtifactSchema(ctx context.Context, request PutArtifactSchemaRequestObject) (PutArtifactSchemaResponseObject, error)

	// (POST /groups/{groupID}/artifacts/{artifactID}/sync)
	TriggerSync(ctx context.Context, request TriggerSyncRequestObject) (TriggerSyncResponseObject, error)

	// (GET /groups/{groupID}/artifacts/{artifactID}/versions)
	GetVersions(ctx context.Context, request GetVersionsRequestObject) (GetVersionsResponseObject, error)

	// (GET /groups/{groupID}/artifacts/{artifactID}/versions/{versionID})
	GetVersionInfo(ctx context.Context, request GetVersionInfoRequestObject) (GetVersionInfoResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetGroups operation middleware
func (sh *strictHandler) GetGroups(w http.ResponseWriter, r *http.Request) {
	var request GetGroupsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGroups(ctx, request.(GetGroupsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGroups")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGroupsResponseObject); ok {
		if err := validResponse.VisitGetGroupsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterGroup operation middleware
func (sh *strictHandler) RegisterGroup(w http.ResponseWriter, r *http.Request) {
	var request RegisterGroupRequestObject

	var body RegisterGroupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterGroup(ctx, request.(RegisterGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterGroupResponseObject); ok {
		if err := validResponse.VisitRegisterGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGroup operation middleware
func (sh *strictHandler) GetGroup(w http.ResponseWriter, r *http.Request, groupID GroupID) {
	var request GetGroupRequestObject

	request.GroupID = groupID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGroup(ctx, request.(GetGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGroupResponseObject); ok {
		if err := validResponse.VisitGetGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArtifacts operation middleware
func (sh *strictHandler) GetArtifacts(w http.ResponseWriter, r *http.Request, groupID GroupID) {
	var request GetArtifactsRequestObject

	request.GroupID = groupID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArtifacts(ctx, request.(GetArtifactsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArtifacts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArtifactsResponseObject); ok {
		if err := validResponse.VisitGetArtifactsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterArtifact operation middleware
func (sh *strictHandler) RegisterArtifact(w http.ResponseWriter, r *http.Request, groupID GroupID) {
	var request RegisterArtifactRequestObject

	request.GroupID = groupID

	var body RegisterArtifactJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterArtifact(ctx, request.(RegisterArtifactRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterArtifact")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterArtifactResponseObject); ok {
		if err := validResponse.VisitRegisterArtifactResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArtifact operation middleware
func (sh *strictHandler) GetArtifact(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID) {
	var request GetArtifactRequestObject

	request.GroupID = groupID
	request.ArtifactID = artifactID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArtifact(ctx, request.(GetArtifactRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArtifact")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArtifactResponseObject); ok {
		if err := validResponse.VisitGetArtifactResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateArtifact operation middleware
func (sh *strictHandler) UpdateArtifact(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID) {
	var request UpdateArtifactRequestObject

	request.GroupID = groupID
	request.ArtifactID = artifactID

	var body UpdateArtifactJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateArtifact(ctx, request.(UpdateArtifactRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateArtifact")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateArtifactResponseObject); ok {
		if err := validResponse.VisitUpdateArtifactResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLatestVersion operation middleware
func (sh *strictHandler) GetLatestVersion(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID, params GetLatestVersionParams) {
	var request GetLatestVersionRequestObject

	request.GroupID = groupID
	request.ArtifactID = artifactID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLatestVersion(ctx, request.(GetLatestVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLatestVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLatestVersionResponseObject); ok {
		if err := validResponse.VisitGetLatestVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArtifactSchema operation middleware
func (sh *strictHandler) GetArtifactSchema(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID) {
	var request GetArtifactSchemaRequestObject

	request.GroupID = groupID
	request.ArtifactID = artifactID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArtifactSchema(ctx, request.(GetArtifactSchemaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArtifactSchema")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArtifactSchemaResponseObject); ok {
		if err := validResponse.VisitGetArtifactSchemaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutArtifactSchema operation middleware
func (sh *strictHandler) PutArtifactSchema(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID) {
	var request PutArtifactSchemaRequestObject

	request.GroupID = groupID
	request.ArtifactID = artifactID

	var body PutArtifactSchemaJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutArtifactSchema(ctx, request.(PutArtifactSchemaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutArtifactSchema")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutArtifactSchemaResponseObject); ok {
		if err := validResponse.VisitPutArtifactSchemaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerSync operation middleware
func (sh *strictHandler) TriggerSync(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID, params TriggerSyncParams) {
	var request TriggerSyncRequestObject

	request.GroupID = groupID
	request.ArtifactID = artifactID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerSync(ctx, request.(TriggerSyncRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerSync")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerSyncResponseObject); ok {
		if err := validResponse.VisitTriggerSyncResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersions operation middleware
func (sh *strictHandler) GetVersions(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID, params GetVersionsParams) {
	var request GetVersionsRequestObject

	request.GroupID = groupID
	request.ArtifactID = artifactID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersions(ctx, request.(GetVersionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionsResponseObject); ok {
		if err := validResponse.VisitGetVersionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersionInfo operation middleware
func (sh *strictHandler) GetVersionInfo(w http.ResponseWriter, r *http.Request, groupID string, artifactID string, versionID string) {
	var request GetVersionInfoRequestObject

	request.GroupID = groupID
	request.ArtifactID = artifactID
	request.VersionID = versionID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersionInfo(ctx, request.(GetVersionInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersionInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionInfoResponseObject); ok {
		if err := validResponse.VisitGetVersionInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
