//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Artifact defines model for Artifact.
type Artifact struct {
	Coordinates struct {
		ArtifactId string `json:"artifactId"`
		GroupId    string `json:"groupId"`
	} `json:"coordinates"`

	// DisplayName The name of the artifact in the desired format to be displayed on the web or referenced in communication
	DisplayName   *string             `json:"displayName,omitempty"`
	GitRepository *[]string           `json:"gitRepository,omitempty"`
	Issues        *string             `json:"issues,omitempty"`
	Tags          map[string][]string `json:"tags"`
	Type          string              `json:"type"`
	Website       *string             `json:"website,omitempty"`
}

// ArtifactRegistration defines model for ArtifactRegistration.
type ArtifactRegistration struct {
	// ArtifactId The maven style artifact id
	ArtifactId string `json:"artifactId"`

	// DisplayName The name of the artifact in the desired format to be displayed on the web or referenced in communication
	DisplayName string `json:"displayName"`

	// GitRepository An array of git repository URLs
	GitRepository []string `json:"gitRepository"`

	// Issues The issues/tracker URL (optional)
	Issues *string `json:"issues,omitempty"`

	// Website The website URL (optional)
	Website *string `json:"website,omitempty"`
}

// Asset defines model for Asset.
type Asset struct {
	// Classifier The classifier of the jar asset. Usually can be
	// understood as the "variant" of the asset. Some
	// variants are specific to an operating sytem, while
	// others are variants of the executable available. In
	// the case of Sponge's main assets, the empty string
	// classifier is the "download and run" asset desired.
	Classifier *string `json:"classifier,omitempty"`

	// DownloadUrl The direct download URL
	DownloadUrl *string `json:"downloadUrl,omitempty"`

	// Extension The file extension of the asset.
	Extension *string `json:"extension,omitempty"`
	Md5       *string `json:"md5,omitempty"`
	Sha1      *string `json:"sha1,omitempty"`
}

// Commit defines model for Commit.
type Commit struct {
	Author *struct {
		Email *string `json:"email,omitempty"`
		Name  *string `json:"name,omitempty"`
	} `json:"author,omitempty"`
	Body       *string             `json:"body,omitempty"`
	CommitDate *openapi_types.Date `json:"commitDate,omitempty"`
	Link       *string             `json:"link,omitempty"`
	Message    *string             `json:"message,omitempty"`
	Sha        *string             `json:"sha,omitempty"`
}

// Group defines model for Group.
type Group struct {
	// GroupCoordinates Maven style group coordinates
	GroupCoordinates string `json:"groupCoordinates"`

	// Name The name of the group
	Name string `json:"name"`

	// Website The website url
	Website *string `json:"website,omitempty"`
}

// GroupArtifacts defines model for GroupArtifacts.
type GroupArtifacts struct {
	// ArtifactIds The artifact id's indexed for the group
	ArtifactIds []string `json:"artifactIds"`
	Type        string   `json:"type"`
}

// Groups defines model for Groups.
type Groups struct {
	Groups []Group `json:"groups"`
}

// ArtifactID defines model for ArtifactID.
type ArtifactID = string

// GroupID defines model for GroupID.
type GroupID = string

// GetVersionsParams defines parameters for GetVersions.
type GetVersionsParams struct {
	Recommended *bool   `form:"recommended,omitempty" json:"recommended,omitempty"`
	Limit       *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset      *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Tags        *string `form:"tags,omitempty" json:"tags,omitempty"`
}

// RegisterGroupJSONRequestBody defines body for RegisterGroup for application/json ContentType.
type RegisterGroupJSONRequestBody = Group

// RegisterArtifactJSONRequestBody defines body for RegisterArtifact for application/json ContentType.
type RegisterArtifactJSONRequestBody = ArtifactRegistration

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /groups)
	GetGroups(w http.ResponseWriter, r *http.Request)

	// (POST /groups)
	RegisterGroup(w http.ResponseWriter, r *http.Request)

	// (GET /groups/{groupID})
	GetGroup(w http.ResponseWriter, r *http.Request, groupID GroupID)

	// (GET /groups/{groupID}/artifacts)
	GetArtifacts(w http.ResponseWriter, r *http.Request, groupID GroupID)

	// (POST /groups/{groupID}/artifacts)
	RegisterArtifact(w http.ResponseWriter, r *http.Request, groupID GroupID)

	// (GET /groups/{groupID}/artifacts/{artifactID})
	GetArtifact(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID)

	// (GET /groups/{groupID}/artifacts/{artifactID}/versions)
	GetVersions(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID, params GetVersionsParams)

	// (GET /groups/{groupID}/artifacts/{artifactID}/versions/{versionID})
	GetVersionInfo(w http.ResponseWriter, r *http.Request, groupID string, artifactID string, versionID string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetGroups operation middleware
func (siw *ServerInterfaceWrapper) GetGroups(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroups(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterGroup operation middleware
func (siw *ServerInterfaceWrapper) RegisterGroup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterGroup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroup(w, r, groupID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArtifacts operation middleware
func (siw *ServerInterfaceWrapper) GetArtifacts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtifacts(w, r, groupID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterArtifact operation middleware
func (siw *ServerInterfaceWrapper) RegisterArtifact(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterArtifact(w, r, groupID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArtifact operation middleware
func (siw *ServerInterfaceWrapper) GetArtifact(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	// ------------- Path parameter "artifactID" -------------
	var artifactID ArtifactID

	err = runtime.BindStyledParameterWithOptions("simple", "artifactID", r.PathValue("artifactID"), &artifactID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artifactID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtifact(w, r, groupID, artifactID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersions operation middleware
func (siw *ServerInterfaceWrapper) GetVersions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID GroupID

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	// ------------- Path parameter "artifactID" -------------
	var artifactID ArtifactID

	err = runtime.BindStyledParameterWithOptions("simple", "artifactID", r.PathValue("artifactID"), &artifactID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artifactID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVersionsParams

	// ------------- Optional query parameter "recommended" -------------

	err = runtime.BindQueryParameter("form", true, false, "recommended", r.URL.Query(), &params.Recommended)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recommended", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "tags" -------------

	err = runtime.BindQueryParameter("form", true, false, "tags", r.URL.Query(), &params.Tags)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tags", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersions(w, r, groupID, artifactID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersionInfo operation middleware
func (siw *ServerInterfaceWrapper) GetVersionInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupID" -------------
	var groupID string

	err = runtime.BindStyledParameterWithOptions("simple", "groupID", r.PathValue("groupID"), &groupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupID", Err: err})
		return
	}

	// ------------- Path parameter "artifactID" -------------
	var artifactID string

	err = runtime.BindStyledParameterWithOptions("simple", "artifactID", r.PathValue("artifactID"), &artifactID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artifactID", Err: err})
		return
	}

	// ------------- Path parameter "versionID" -------------
	var versionID string

	err = runtime.BindStyledParameterWithOptions("simple", "versionID", r.PathValue("versionID"), &versionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "versionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersionInfo(w, r, groupID, artifactID, versionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/groups", wrapper.GetGroups)
	m.HandleFunc("POST "+options.BaseURL+"/groups", wrapper.RegisterGroup)
	m.HandleFunc("GET "+options.BaseURL+"/groups/{groupID}", wrapper.GetGroup)
	m.HandleFunc("GET "+options.BaseURL+"/groups/{groupID}/artifacts", wrapper.GetArtifacts)
	m.HandleFunc("POST "+options.BaseURL+"/groups/{groupID}/artifacts", wrapper.RegisterArtifact)
	m.HandleFunc("GET "+options.BaseURL+"/groups/{groupID}/artifacts/{artifactID}", wrapper.GetArtifact)
	m.HandleFunc("GET "+options.BaseURL+"/groups/{groupID}/artifacts/{artifactID}/versions", wrapper.GetVersions)
	m.HandleFunc("GET "+options.BaseURL+"/groups/{groupID}/artifacts/{artifactID}/versions/{versionID}", wrapper.GetVersionInfo)

	return m
}

type GetGroupsRequestObject struct {
}

type GetGroupsResponseObject interface {
	VisitGetGroupsResponse(w http.ResponseWriter) error
}

type GetGroups200JSONResponse Groups

func (response GetGroups200JSONResponse) VisitGetGroupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RegisterGroupRequestObject struct {
	Body *RegisterGroupJSONRequestBody
}

type RegisterGroupResponseObject interface {
	VisitRegisterGroupResponse(w http.ResponseWriter) error
}

type RegisterGroup201JSONResponse Group

func (response RegisterGroup201JSONResponse) VisitRegisterGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type GetGroupRequestObject struct {
	GroupID GroupID `json:"groupID"`
}

type GetGroupResponseObject interface {
	VisitGetGroupResponse(w http.ResponseWriter) error
}

type GetGroup200JSONResponse Group

func (response GetGroup200JSONResponse) VisitGetGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArtifactsRequestObject struct {
	GroupID GroupID `json:"groupID"`
}

type GetArtifactsResponseObject interface {
	VisitGetArtifactsResponse(w http.ResponseWriter) error
}

type GetArtifacts200JSONResponse GroupArtifacts

func (response GetArtifacts200JSONResponse) VisitGetArtifactsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RegisterArtifactRequestObject struct {
	GroupID GroupID `json:"groupID"`
	Body    *RegisterArtifactJSONRequestBody
}

type RegisterArtifactResponseObject interface {
	VisitRegisterArtifactResponse(w http.ResponseWriter) error
}

type RegisterArtifact201JSONResponse Artifact

func (response RegisterArtifact201JSONResponse) VisitRegisterArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterArtifact400Response struct {
}

func (response RegisterArtifact400Response) VisitRegisterArtifactResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type RegisterArtifact404Response struct {
}

func (response RegisterArtifact404Response) VisitRegisterArtifactResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type RegisterArtifact409Response struct {
}

func (response RegisterArtifact409Response) VisitRegisterArtifactResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type GetArtifactRequestObject struct {
	GroupID    GroupID    `json:"groupID"`
	ArtifactID ArtifactID `json:"artifactID"`
}

type GetArtifactResponseObject interface {
	VisitGetArtifactResponse(w http.ResponseWriter) error
}

type GetArtifact200JSONResponse Artifact

func (response GetArtifact200JSONResponse) VisitGetArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVersionsRequestObject struct {
	GroupID    GroupID    `json:"groupID"`
	ArtifactID ArtifactID `json:"artifactID"`
	Params     GetVersionsParams
}

type GetVersionsResponseObject interface {
	VisitGetVersionsResponse(w http.ResponseWriter) error
}

type GetVersions200JSONResponse struct {
	Artifacts *map[string]map[string]struct {
		Recommended *bool              `json:"recommended,omitempty"`
		TagValues   *map[string]string `json:"tagValues,omitempty"`
	} `json:"artifacts,omitempty"`
}

func (response GetVersions200JSONResponse) VisitGetVersionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVersionInfoRequestObject struct {
	GroupID    string `json:"groupID"`
	ArtifactID string `json:"artifactID"`
	VersionID  string `json:"versionID"`
}

type GetVersionInfoResponseObject interface {
	VisitGetVersionInfoResponse(w http.ResponseWriter) error
}

type GetVersionInfo200JSONResponse struct {
	Assets *[]Asset `json:"assets,omitempty"`
	Commit *struct {
		Commits *[]struct {
			Commit           *Commit   `json:"commit,omitempty"`
			SubmoduleCommits *[]Commit `json:"submoduleCommits,omitempty"`
		} `json:"commits,omitempty"`
	} `json:"commit,omitempty"`
	Coordinates *struct {
		ArtifactId *string `json:"artifactId,omitempty"`
		GroupId    *string `json:"groupId,omitempty"`
		Version    *string `json:"version,omitempty"`
	} `json:"coordinates,omitempty"`

	// Recommended Whether the artifact is considered a "standard release" version or if it is still in development.
	Recommended *bool              `json:"recommended,omitempty"`
	Tags        *map[string]string `json:"tags,omitempty"`
}

func (response GetVersionInfo200JSONResponse) VisitGetVersionInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /groups)
	GetGroups(ctx context.Context, request GetGroupsRequestObject) (GetGroupsResponseObject, error)

	// (POST /groups)
	RegisterGroup(ctx context.Context, request RegisterGroupRequestObject) (RegisterGroupResponseObject, error)

	// (GET /groups/{groupID})
	GetGroup(ctx context.Context, request GetGroupRequestObject) (GetGroupResponseObject, error)

	// (GET /groups/{groupID}/artifacts)
	GetArtifacts(ctx context.Context, request GetArtifactsRequestObject) (GetArtifactsResponseObject, error)

	// (POST /groups/{groupID}/artifacts)
	RegisterArtifact(ctx context.Context, request RegisterArtifactRequestObject) (RegisterArtifactResponseObject, error)

	// (GET /groups/{groupID}/artifacts/{artifactID})
	GetArtifact(ctx context.Context, request GetArtifactRequestObject) (GetArtifactResponseObject, error)

	// (GET /groups/{groupID}/artifacts/{artifactID}/versions)
	GetVersions(ctx context.Context, request GetVersionsRequestObject) (GetVersionsResponseObject, error)

	// (GET /groups/{groupID}/artifacts/{artifactID}/versions/{versionID})
	GetVersionInfo(ctx context.Context, request GetVersionInfoRequestObject) (GetVersionInfoResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetGroups operation middleware
func (sh *strictHandler) GetGroups(w http.ResponseWriter, r *http.Request) {
	var request GetGroupsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGroups(ctx, request.(GetGroupsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGroups")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGroupsResponseObject); ok {
		if err := validResponse.VisitGetGroupsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterGroup operation middleware
func (sh *strictHandler) RegisterGroup(w http.ResponseWriter, r *http.Request) {
	var request RegisterGroupRequestObject

	var body RegisterGroupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterGroup(ctx, request.(RegisterGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterGroupResponseObject); ok {
		if err := validResponse.VisitRegisterGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGroup operation middleware
func (sh *strictHandler) GetGroup(w http.ResponseWriter, r *http.Request, groupID GroupID) {
	var request GetGroupRequestObject

	request.GroupID = groupID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGroup(ctx, request.(GetGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGroupResponseObject); ok {
		if err := validResponse.VisitGetGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArtifacts operation middleware
func (sh *strictHandler) GetArtifacts(w http.ResponseWriter, r *http.Request, groupID GroupID) {
	var request GetArtifactsRequestObject

	request.GroupID = groupID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArtifacts(ctx, request.(GetArtifactsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArtifacts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArtifactsResponseObject); ok {
		if err := validResponse.VisitGetArtifactsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterArtifact operation middleware
func (sh *strictHandler) RegisterArtifact(w http.ResponseWriter, r *http.Request, groupID GroupID) {
	var request RegisterArtifactRequestObject

	request.GroupID = groupID

	var body RegisterArtifactJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterArtifact(ctx, request.(RegisterArtifactRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterArtifact")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterArtifactResponseObject); ok {
		if err := validResponse.VisitRegisterArtifactResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArtifact operation middleware
func (sh *strictHandler) GetArtifact(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID) {
	var request GetArtifactRequestObject

	request.GroupID = groupID
	request.ArtifactID = artifactID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetArtifact(ctx, request.(GetArtifactRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArtifact")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetArtifactResponseObject); ok {
		if err := validResponse.VisitGetArtifactResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersions operation middleware
func (sh *strictHandler) GetVersions(w http.ResponseWriter, r *http.Request, groupID GroupID, artifactID ArtifactID, params GetVersionsParams) {
	var request GetVersionsRequestObject

	request.GroupID = groupID
	request.ArtifactID = artifactID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersions(ctx, request.(GetVersionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionsResponseObject); ok {
		if err := validResponse.VisitGetVersionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersionInfo operation middleware
func (sh *strictHandler) GetVersionInfo(w http.ResponseWriter, r *http.Request, groupID string, artifactID string, versionID string) {
	var request GetVersionInfoRequestObject

	request.GroupID = groupID
	request.ArtifactID = artifactID
	request.VersionID = versionID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersionInfo(ctx, request.(GetVersionInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersionInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionInfoResponseObject); ok {
		if err := validResponse.VisitGetVersionInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
