name: Build and Verify

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8 --illegal-access=permit
            JVM_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8 --illegal-access=permit
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up SBT
                uses: olafurpg/setup-scala@v10
                with:
                    java-version: adopt@1.16
            -   name: Build with SBT
                run: sbt -v test
    publish:
        needs: test
        runs-on: ubuntu-latest
        env:
            JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8 --illegal-access=permit
            JVM_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8 --illegal-access=permit
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up SBT
                uses: olafurpg/setup-scala@v10
                with:
                    java-version: adopt@1.16
            -   name: Build with SBT
                run: sbt -v docker:publishLocal
